/* Generated by Yosys 0.7+307 (git sha1 7d41c5e1, gcc 7.2.0-3ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "execute.v:33" *)
module status_register_adaptor(st, stwr, n, z, c, v, cc);
  (* src = "execute.v:34" *)
  input c;
  (* src = "execute.v:35" *)
  input cc;
  (* src = "execute.v:34" *)
  input n;
  (* src = "execute.v:37" *)
  output [31:0] st;
  (* src = "execute.v:38" *)
  output stwr;
  (* src = "execute.v:34" *)
  input v;
  (* src = "execute.v:34" *)
  input z;
  assign st = { 28'h0000000, n, z, c, v };
  assign stwr = cc;
endmodule
