/* Generated by Yosys 0.7+307 (git sha1 7d41c5e1, gcc 6.3.0-18 -fPIC -Os) */

(* top =  1  *)
(* src = "gpio_mux.v:3" *)
module gpio_mux(pins, func0_in, func1_in, func2_in, func3_in, func0_out, func1_out, func2_out, func3_out, func0_dir, func1_dir, func2_dir, func3_dir, addr, sys_w_addr, sys_r_addr, sys_w_line, sys_r_line, sys_w, sys_r, rst, clk);
  (* src = "gpio_mux.v:58" *)
  wire [63:0] _000_;
  (* src = "gpio_mux.v:58" *)
  wire [31:0] _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire _310_;
  wire _311_;
  wire _312_;
  wire _313_;
  wire _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire _319_;
  wire _320_;
  wire _321_;
  wire _322_;
  wire _323_;
  wire _324_;
  wire _325_;
  wire _326_;
  wire _327_;
  wire _328_;
  wire _329_;
  wire _330_;
  wire _331_;
  wire _332_;
  wire _333_;
  wire _334_;
  wire _335_;
  wire _336_;
  wire _337_;
  wire _338_;
  wire _339_;
  wire _340_;
  wire _341_;
  wire _342_;
  wire _343_;
  wire _344_;
  wire _345_;
  wire _346_;
  wire _347_;
  wire _348_;
  wire _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  (* src = "gpio_mux.v:26" *)
  input [31:0] addr;
  (* src = "gpio_mux.v:37" *)
  input clk;
  (* src = "gpio_mux.v:41" *)
  wire [63:0] control;
  (* src = "gpio_mux.v:20" *)
  input [31:0] func0_dir;
  (* src = "gpio_mux.v:14" *)
  output [31:0] func0_in;
  (* src = "gpio_mux.v:8" *)
  input [31:0] func0_out;
  (* src = "gpio_mux.v:21" *)
  input [31:0] func1_dir;
  (* src = "gpio_mux.v:15" *)
  output [31:0] func1_in;
  (* src = "gpio_mux.v:9" *)
  input [31:0] func1_out;
  (* src = "gpio_mux.v:22" *)
  input [31:0] func2_dir;
  (* src = "gpio_mux.v:16" *)
  output [31:0] func2_in;
  (* src = "gpio_mux.v:10" *)
  input [31:0] func2_out;
  (* src = "gpio_mux.v:23" *)
  input [31:0] func3_dir;
  (* src = "gpio_mux.v:17" *)
  output [31:0] func3_in;
  (* src = "gpio_mux.v:11" *)
  input [31:0] func3_out;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[0].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[0].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[10].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[10].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[11].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[11].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[12].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[12].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[13].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[13].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[14].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[14].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[15].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[15].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[16].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[16].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[17].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[17].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[18].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[18].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[19].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[19].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[1].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[1].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[20].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[20].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[21].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[21].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[22].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[22].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[23].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[23].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[24].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[24].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[25].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[25].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[26].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[26].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[27].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[27].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[28].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[28].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[29].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[29].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[2].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[2].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[30].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[30].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[31].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[31].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[3].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[3].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[4].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[4].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[5].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[5].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[6].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[6].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[7].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[7].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[8].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[8].pin_out ;
  (* src = "gpio_mux.v:47" *)
  wire [1:0] \pin_mux[9].pin_control ;
  (* src = "gpio_mux.v:48" *)
  wire \pin_mux[9].pin_out ;
  (* src = "gpio_mux.v:4" *)
  inout [31:0] pins;
  (* src = "gpio_mux.v:38" *)
  input rst;
  (* src = "gpio_mux.v:34" *)
  input sys_r;
  (* src = "gpio_mux.v:30" *)
  input [31:0] sys_r_addr;
  (* src = "gpio_mux.v:32" *)
  output [31:0] sys_r_line;
  (* src = "gpio_mux.v:33" *)
  input sys_w;
  (* src = "gpio_mux.v:29" *)
  input [31:0] sys_w_addr;
  (* src = "gpio_mux.v:31" *)
  input [31:0] sys_w_line;
  INVX1 _361_ (
    .A(rst),
    .Y(_002_)
  );
  INVX1 _362_ (
    .A(control[8]),
    .Y(_003_)
  );
  INVX1 _363_ (
    .A(control[9]),
    .Y(_004_)
  );
  INVX1 _364_ (
    .A(control[10]),
    .Y(_005_)
  );
  INVX1 _365_ (
    .A(control[11]),
    .Y(_006_)
  );
  INVX1 _366_ (
    .A(control[12]),
    .Y(_007_)
  );
  INVX1 _367_ (
    .A(control[13]),
    .Y(_008_)
  );
  INVX1 _368_ (
    .A(control[14]),
    .Y(_009_)
  );
  INVX1 _369_ (
    .A(control[15]),
    .Y(_010_)
  );
  INVX1 _370_ (
    .A(control[16]),
    .Y(_011_)
  );
  INVX1 _371_ (
    .A(control[17]),
    .Y(_012_)
  );
  INVX1 _372_ (
    .A(control[18]),
    .Y(_013_)
  );
  INVX1 _373_ (
    .A(control[19]),
    .Y(_014_)
  );
  INVX1 _374_ (
    .A(control[20]),
    .Y(_015_)
  );
  INVX1 _375_ (
    .A(control[21]),
    .Y(_016_)
  );
  INVX1 _376_ (
    .A(control[22]),
    .Y(_017_)
  );
  INVX1 _377_ (
    .A(control[23]),
    .Y(_018_)
  );
  INVX1 _378_ (
    .A(control[24]),
    .Y(_019_)
  );
  INVX1 _379_ (
    .A(control[25]),
    .Y(_020_)
  );
  INVX1 _380_ (
    .A(control[26]),
    .Y(_021_)
  );
  INVX1 _381_ (
    .A(control[27]),
    .Y(_022_)
  );
  INVX1 _382_ (
    .A(control[28]),
    .Y(_023_)
  );
  INVX1 _383_ (
    .A(control[29]),
    .Y(_024_)
  );
  INVX1 _384_ (
    .A(control[30]),
    .Y(_025_)
  );
  INVX1 _385_ (
    .A(control[31]),
    .Y(_026_)
  );
  INVX1 _386_ (
    .A(control[32]),
    .Y(_027_)
  );
  INVX1 _387_ (
    .A(control[33]),
    .Y(_028_)
  );
  INVX1 _388_ (
    .A(control[34]),
    .Y(_029_)
  );
  INVX1 _389_ (
    .A(control[35]),
    .Y(_030_)
  );
  INVX1 _390_ (
    .A(control[36]),
    .Y(_031_)
  );
  INVX1 _391_ (
    .A(control[37]),
    .Y(_032_)
  );
  INVX1 _392_ (
    .A(control[38]),
    .Y(_033_)
  );
  INVX1 _393_ (
    .A(control[39]),
    .Y(_034_)
  );
  INVX1 _394_ (
    .A(control[40]),
    .Y(_035_)
  );
  INVX1 _395_ (
    .A(control[41]),
    .Y(_036_)
  );
  INVX1 _396_ (
    .A(control[42]),
    .Y(_037_)
  );
  INVX1 _397_ (
    .A(control[43]),
    .Y(_038_)
  );
  INVX1 _398_ (
    .A(control[44]),
    .Y(_039_)
  );
  INVX1 _399_ (
    .A(control[45]),
    .Y(_040_)
  );
  INVX1 _400_ (
    .A(control[46]),
    .Y(_041_)
  );
  INVX1 _401_ (
    .A(control[47]),
    .Y(_042_)
  );
  INVX1 _402_ (
    .A(control[48]),
    .Y(_043_)
  );
  INVX1 _403_ (
    .A(control[49]),
    .Y(_044_)
  );
  INVX1 _404_ (
    .A(control[50]),
    .Y(_045_)
  );
  INVX1 _405_ (
    .A(control[51]),
    .Y(_046_)
  );
  INVX1 _406_ (
    .A(control[52]),
    .Y(_047_)
  );
  INVX1 _407_ (
    .A(control[53]),
    .Y(_048_)
  );
  INVX1 _408_ (
    .A(control[54]),
    .Y(_049_)
  );
  INVX1 _409_ (
    .A(control[55]),
    .Y(_050_)
  );
  INVX1 _410_ (
    .A(control[56]),
    .Y(_051_)
  );
  INVX1 _411_ (
    .A(control[57]),
    .Y(_052_)
  );
  INVX1 _412_ (
    .A(control[58]),
    .Y(_053_)
  );
  INVX1 _413_ (
    .A(control[59]),
    .Y(_054_)
  );
  INVX1 _414_ (
    .A(control[60]),
    .Y(_055_)
  );
  INVX1 _415_ (
    .A(control[61]),
    .Y(_056_)
  );
  INVX1 _416_ (
    .A(control[62]),
    .Y(_057_)
  );
  INVX1 _417_ (
    .A(control[63]),
    .Y(_058_)
  );
  INVX1 _418_ (
    .A(sys_w_line[0]),
    .Y(_059_)
  );
  INVX1 _419_ (
    .A(control[0]),
    .Y(_060_)
  );
  INVX1 _420_ (
    .A(sys_w_addr[0]),
    .Y(_061_)
  );
  INVX1 _421_ (
    .A(addr[2]),
    .Y(_062_)
  );
  INVX1 _422_ (
    .A(sys_w_addr[2]),
    .Y(_063_)
  );
  INVX1 _423_ (
    .A(addr[3]),
    .Y(_064_)
  );
  INVX1 _424_ (
    .A(sys_w_addr[3]),
    .Y(_065_)
  );
  INVX1 _425_ (
    .A(sys_w_addr[7]),
    .Y(_066_)
  );
  INVX1 _426_ (
    .A(sys_w_addr[12]),
    .Y(_067_)
  );
  INVX1 _427_ (
    .A(addr[18]),
    .Y(_068_)
  );
  INVX1 _428_ (
    .A(sys_w_addr[18]),
    .Y(_069_)
  );
  INVX1 _429_ (
    .A(addr[20]),
    .Y(_070_)
  );
  INVX1 _430_ (
    .A(addr[26]),
    .Y(_071_)
  );
  INVX1 _431_ (
    .A(sys_w_addr[26]),
    .Y(_072_)
  );
  INVX1 _432_ (
    .A(sys_w_line[1]),
    .Y(_073_)
  );
  INVX1 _433_ (
    .A(control[1]),
    .Y(_074_)
  );
  INVX1 _434_ (
    .A(sys_w_line[2]),
    .Y(_075_)
  );
  INVX1 _435_ (
    .A(control[2]),
    .Y(_076_)
  );
  INVX1 _436_ (
    .A(sys_w_line[3]),
    .Y(_077_)
  );
  INVX1 _437_ (
    .A(control[3]),
    .Y(_078_)
  );
  INVX1 _438_ (
    .A(sys_w_line[4]),
    .Y(_079_)
  );
  INVX1 _439_ (
    .A(control[4]),
    .Y(_080_)
  );
  INVX1 _440_ (
    .A(sys_w_line[5]),
    .Y(_081_)
  );
  INVX1 _441_ (
    .A(control[5]),
    .Y(_082_)
  );
  INVX1 _442_ (
    .A(sys_w_line[6]),
    .Y(_083_)
  );
  INVX1 _443_ (
    .A(control[6]),
    .Y(_084_)
  );
  INVX1 _444_ (
    .A(sys_w_line[7]),
    .Y(_085_)
  );
  INVX1 _445_ (
    .A(control[7]),
    .Y(_086_)
  );
  INVX1 _446_ (
    .A(sys_w_line[8]),
    .Y(_087_)
  );
  INVX1 _447_ (
    .A(sys_w_line[9]),
    .Y(_088_)
  );
  INVX1 _448_ (
    .A(sys_w_line[10]),
    .Y(_089_)
  );
  INVX1 _449_ (
    .A(sys_w_line[11]),
    .Y(_090_)
  );
  INVX1 _450_ (
    .A(sys_w_line[12]),
    .Y(_091_)
  );
  INVX1 _451_ (
    .A(sys_w_line[13]),
    .Y(_092_)
  );
  INVX1 _452_ (
    .A(sys_w_line[14]),
    .Y(_093_)
  );
  INVX1 _453_ (
    .A(sys_w_line[15]),
    .Y(_094_)
  );
  INVX1 _454_ (
    .A(sys_w_line[16]),
    .Y(_095_)
  );
  INVX1 _455_ (
    .A(sys_w_line[17]),
    .Y(_096_)
  );
  INVX1 _456_ (
    .A(sys_w_line[18]),
    .Y(_097_)
  );
  INVX1 _457_ (
    .A(sys_w_line[19]),
    .Y(_098_)
  );
  INVX1 _458_ (
    .A(sys_w_line[20]),
    .Y(_099_)
  );
  INVX1 _459_ (
    .A(sys_w_line[21]),
    .Y(_100_)
  );
  INVX1 _460_ (
    .A(sys_w_line[22]),
    .Y(_101_)
  );
  INVX1 _461_ (
    .A(sys_w_line[23]),
    .Y(_102_)
  );
  INVX1 _462_ (
    .A(sys_w_line[24]),
    .Y(_103_)
  );
  INVX1 _463_ (
    .A(sys_w_line[25]),
    .Y(_104_)
  );
  INVX1 _464_ (
    .A(sys_w_line[26]),
    .Y(_105_)
  );
  INVX1 _465_ (
    .A(sys_w_line[27]),
    .Y(_106_)
  );
  INVX1 _466_ (
    .A(sys_w_line[28]),
    .Y(_107_)
  );
  INVX1 _467_ (
    .A(sys_w_line[29]),
    .Y(_108_)
  );
  INVX1 _468_ (
    .A(sys_w_line[30]),
    .Y(_109_)
  );
  INVX1 _469_ (
    .A(sys_w_line[31]),
    .Y(_110_)
  );
  NOR2X1 _470_ (
    .A(control[8]),
    .B(func2_out[4]),
    .Y(_111_)
  );
  MUX2X1 _471_ (
    .A(func1_out[4]),
    .B(func0_out[4]),
    .S(control[8]),
    .Y(_112_)
  );
  OAI21X1 _472_ (
    .A(_003_),
    .B(func3_out[4]),
    .C(control[9]),
    .Y(_113_)
  );
  OAI22X1 _473_ (
    .A(control[9]),
    .B(_112_),
    .C(_113_),
    .D(_111_),
    .Y(pins[4])
  );
  NOR2X1 _474_ (
    .A(control[10]),
    .B(func2_out[5]),
    .Y(_114_)
  );
  MUX2X1 _475_ (
    .A(func1_out[5]),
    .B(func0_out[5]),
    .S(control[10]),
    .Y(_115_)
  );
  OAI21X1 _476_ (
    .A(_005_),
    .B(func3_out[5]),
    .C(control[11]),
    .Y(_116_)
  );
  OAI22X1 _477_ (
    .A(control[11]),
    .B(_115_),
    .C(_116_),
    .D(_114_),
    .Y(pins[5])
  );
  NOR2X1 _478_ (
    .A(control[12]),
    .B(func2_out[6]),
    .Y(_117_)
  );
  MUX2X1 _479_ (
    .A(func1_out[6]),
    .B(func0_out[6]),
    .S(control[12]),
    .Y(_118_)
  );
  OAI21X1 _480_ (
    .A(_007_),
    .B(func3_out[6]),
    .C(control[13]),
    .Y(_119_)
  );
  OAI22X1 _481_ (
    .A(control[13]),
    .B(_118_),
    .C(_119_),
    .D(_117_),
    .Y(pins[6])
  );
  NOR2X1 _482_ (
    .A(control[14]),
    .B(func2_out[7]),
    .Y(_120_)
  );
  MUX2X1 _483_ (
    .A(func1_out[7]),
    .B(func0_out[7]),
    .S(control[14]),
    .Y(_121_)
  );
  OAI21X1 _484_ (
    .A(_009_),
    .B(func3_out[7]),
    .C(control[15]),
    .Y(_122_)
  );
  OAI22X1 _485_ (
    .A(control[15]),
    .B(_121_),
    .C(_122_),
    .D(_120_),
    .Y(pins[7])
  );
  NOR2X1 _486_ (
    .A(control[16]),
    .B(func2_out[8]),
    .Y(_123_)
  );
  MUX2X1 _487_ (
    .A(func1_out[8]),
    .B(func0_out[8]),
    .S(control[16]),
    .Y(_124_)
  );
  OAI21X1 _488_ (
    .A(_011_),
    .B(func3_out[8]),
    .C(control[17]),
    .Y(_125_)
  );
  OAI22X1 _489_ (
    .A(control[17]),
    .B(_124_),
    .C(_125_),
    .D(_123_),
    .Y(pins[8])
  );
  NOR2X1 _490_ (
    .A(control[18]),
    .B(func2_out[9]),
    .Y(_126_)
  );
  MUX2X1 _491_ (
    .A(func1_out[9]),
    .B(func0_out[9]),
    .S(control[18]),
    .Y(_127_)
  );
  OAI21X1 _492_ (
    .A(_013_),
    .B(func3_out[9]),
    .C(control[19]),
    .Y(_128_)
  );
  OAI22X1 _493_ (
    .A(control[19]),
    .B(_127_),
    .C(_128_),
    .D(_126_),
    .Y(pins[9])
  );
  NOR2X1 _494_ (
    .A(control[20]),
    .B(func2_out[10]),
    .Y(_129_)
  );
  MUX2X1 _495_ (
    .A(func1_out[10]),
    .B(func0_out[10]),
    .S(control[20]),
    .Y(_130_)
  );
  OAI21X1 _496_ (
    .A(_015_),
    .B(func3_out[10]),
    .C(control[21]),
    .Y(_131_)
  );
  OAI22X1 _497_ (
    .A(control[21]),
    .B(_130_),
    .C(_131_),
    .D(_129_),
    .Y(pins[10])
  );
  NOR2X1 _498_ (
    .A(control[22]),
    .B(func2_out[11]),
    .Y(_132_)
  );
  MUX2X1 _499_ (
    .A(func1_out[11]),
    .B(func0_out[11]),
    .S(control[22]),
    .Y(_133_)
  );
  OAI21X1 _500_ (
    .A(_017_),
    .B(func3_out[11]),
    .C(control[23]),
    .Y(_134_)
  );
  OAI22X1 _501_ (
    .A(control[23]),
    .B(_133_),
    .C(_134_),
    .D(_132_),
    .Y(pins[11])
  );
  NOR2X1 _502_ (
    .A(control[24]),
    .B(func2_out[12]),
    .Y(_135_)
  );
  MUX2X1 _503_ (
    .A(func1_out[12]),
    .B(func0_out[12]),
    .S(control[24]),
    .Y(_136_)
  );
  OAI21X1 _504_ (
    .A(_019_),
    .B(func3_out[12]),
    .C(control[25]),
    .Y(_137_)
  );
  OAI22X1 _505_ (
    .A(control[25]),
    .B(_136_),
    .C(_137_),
    .D(_135_),
    .Y(pins[12])
  );
  NOR2X1 _506_ (
    .A(control[26]),
    .B(func2_out[13]),
    .Y(_138_)
  );
  MUX2X1 _507_ (
    .A(func1_out[13]),
    .B(func0_out[13]),
    .S(control[26]),
    .Y(_139_)
  );
  OAI21X1 _508_ (
    .A(_021_),
    .B(func3_out[13]),
    .C(control[27]),
    .Y(_140_)
  );
  OAI22X1 _509_ (
    .A(control[27]),
    .B(_139_),
    .C(_140_),
    .D(_138_),
    .Y(pins[13])
  );
  NOR2X1 _510_ (
    .A(control[28]),
    .B(func2_out[14]),
    .Y(_141_)
  );
  MUX2X1 _511_ (
    .A(func1_out[14]),
    .B(func0_out[14]),
    .S(control[28]),
    .Y(_142_)
  );
  OAI21X1 _512_ (
    .A(_023_),
    .B(func3_out[14]),
    .C(control[29]),
    .Y(_143_)
  );
  OAI22X1 _513_ (
    .A(control[29]),
    .B(_142_),
    .C(_143_),
    .D(_141_),
    .Y(pins[14])
  );
  NOR2X1 _514_ (
    .A(control[30]),
    .B(func2_out[15]),
    .Y(_144_)
  );
  MUX2X1 _515_ (
    .A(func1_out[15]),
    .B(func0_out[15]),
    .S(control[30]),
    .Y(_145_)
  );
  OAI21X1 _516_ (
    .A(_025_),
    .B(func3_out[15]),
    .C(control[31]),
    .Y(_146_)
  );
  OAI22X1 _517_ (
    .A(control[31]),
    .B(_145_),
    .C(_146_),
    .D(_144_),
    .Y(pins[15])
  );
  NOR2X1 _518_ (
    .A(control[32]),
    .B(func2_out[16]),
    .Y(_147_)
  );
  MUX2X1 _519_ (
    .A(func1_out[16]),
    .B(func0_out[16]),
    .S(control[32]),
    .Y(_148_)
  );
  OAI21X1 _520_ (
    .A(_027_),
    .B(func3_out[16]),
    .C(control[33]),
    .Y(_149_)
  );
  OAI22X1 _521_ (
    .A(control[33]),
    .B(_148_),
    .C(_149_),
    .D(_147_),
    .Y(pins[16])
  );
  NOR2X1 _522_ (
    .A(control[34]),
    .B(func2_out[17]),
    .Y(_150_)
  );
  MUX2X1 _523_ (
    .A(func1_out[17]),
    .B(func0_out[17]),
    .S(control[34]),
    .Y(_151_)
  );
  OAI21X1 _524_ (
    .A(_029_),
    .B(func3_out[17]),
    .C(control[35]),
    .Y(_152_)
  );
  OAI22X1 _525_ (
    .A(control[35]),
    .B(_151_),
    .C(_152_),
    .D(_150_),
    .Y(pins[17])
  );
  NOR2X1 _526_ (
    .A(control[36]),
    .B(func2_out[18]),
    .Y(_153_)
  );
  MUX2X1 _527_ (
    .A(func1_out[18]),
    .B(func0_out[18]),
    .S(control[36]),
    .Y(_154_)
  );
  OAI21X1 _528_ (
    .A(_031_),
    .B(func3_out[18]),
    .C(control[37]),
    .Y(_155_)
  );
  OAI22X1 _529_ (
    .A(control[37]),
    .B(_154_),
    .C(_155_),
    .D(_153_),
    .Y(pins[18])
  );
  NOR2X1 _530_ (
    .A(control[38]),
    .B(func2_out[19]),
    .Y(_156_)
  );
  MUX2X1 _531_ (
    .A(func1_out[19]),
    .B(func0_out[19]),
    .S(control[38]),
    .Y(_157_)
  );
  OAI21X1 _532_ (
    .A(_033_),
    .B(func3_out[19]),
    .C(control[39]),
    .Y(_158_)
  );
  OAI22X1 _533_ (
    .A(control[39]),
    .B(_157_),
    .C(_158_),
    .D(_156_),
    .Y(pins[19])
  );
  NOR2X1 _534_ (
    .A(control[40]),
    .B(func2_out[20]),
    .Y(_159_)
  );
  MUX2X1 _535_ (
    .A(func1_out[20]),
    .B(func0_out[20]),
    .S(control[40]),
    .Y(_160_)
  );
  OAI21X1 _536_ (
    .A(_035_),
    .B(func3_out[20]),
    .C(control[41]),
    .Y(_161_)
  );
  OAI22X1 _537_ (
    .A(control[41]),
    .B(_160_),
    .C(_161_),
    .D(_159_),
    .Y(pins[20])
  );
  NOR2X1 _538_ (
    .A(control[42]),
    .B(func2_out[21]),
    .Y(_162_)
  );
  MUX2X1 _539_ (
    .A(func1_out[21]),
    .B(func0_out[21]),
    .S(control[42]),
    .Y(_163_)
  );
  OAI21X1 _540_ (
    .A(_037_),
    .B(func3_out[21]),
    .C(control[43]),
    .Y(_164_)
  );
  OAI22X1 _541_ (
    .A(control[43]),
    .B(_163_),
    .C(_164_),
    .D(_162_),
    .Y(pins[21])
  );
  NOR2X1 _542_ (
    .A(control[44]),
    .B(func2_out[22]),
    .Y(_165_)
  );
  MUX2X1 _543_ (
    .A(func1_out[22]),
    .B(func0_out[22]),
    .S(control[44]),
    .Y(_166_)
  );
  OAI21X1 _544_ (
    .A(_039_),
    .B(func3_out[22]),
    .C(control[45]),
    .Y(_167_)
  );
  OAI22X1 _545_ (
    .A(control[45]),
    .B(_166_),
    .C(_167_),
    .D(_165_),
    .Y(pins[22])
  );
  NOR2X1 _546_ (
    .A(control[46]),
    .B(func2_out[23]),
    .Y(_168_)
  );
  MUX2X1 _547_ (
    .A(func1_out[23]),
    .B(func0_out[23]),
    .S(control[46]),
    .Y(_169_)
  );
  OAI21X1 _548_ (
    .A(_041_),
    .B(func3_out[23]),
    .C(control[47]),
    .Y(_170_)
  );
  OAI22X1 _549_ (
    .A(control[47]),
    .B(_169_),
    .C(_170_),
    .D(_168_),
    .Y(pins[23])
  );
  NOR2X1 _550_ (
    .A(control[48]),
    .B(func2_out[24]),
    .Y(_171_)
  );
  MUX2X1 _551_ (
    .A(func1_out[24]),
    .B(func0_out[24]),
    .S(control[48]),
    .Y(_172_)
  );
  OAI21X1 _552_ (
    .A(_043_),
    .B(func3_out[24]),
    .C(control[49]),
    .Y(_173_)
  );
  OAI22X1 _553_ (
    .A(control[49]),
    .B(_172_),
    .C(_173_),
    .D(_171_),
    .Y(pins[24])
  );
  NOR2X1 _554_ (
    .A(control[50]),
    .B(func2_out[25]),
    .Y(_174_)
  );
  MUX2X1 _555_ (
    .A(func1_out[25]),
    .B(func0_out[25]),
    .S(control[50]),
    .Y(_175_)
  );
  OAI21X1 _556_ (
    .A(_045_),
    .B(func3_out[25]),
    .C(control[51]),
    .Y(_176_)
  );
  OAI22X1 _557_ (
    .A(control[51]),
    .B(_175_),
    .C(_176_),
    .D(_174_),
    .Y(pins[25])
  );
  NOR2X1 _558_ (
    .A(control[52]),
    .B(func2_out[26]),
    .Y(_177_)
  );
  MUX2X1 _559_ (
    .A(func1_out[26]),
    .B(func0_out[26]),
    .S(control[52]),
    .Y(_178_)
  );
  OAI21X1 _560_ (
    .A(_047_),
    .B(func3_out[26]),
    .C(control[53]),
    .Y(_179_)
  );
  OAI22X1 _561_ (
    .A(control[53]),
    .B(_178_),
    .C(_179_),
    .D(_177_),
    .Y(pins[26])
  );
  NOR2X1 _562_ (
    .A(control[54]),
    .B(func2_out[27]),
    .Y(_180_)
  );
  MUX2X1 _563_ (
    .A(func1_out[27]),
    .B(func0_out[27]),
    .S(control[54]),
    .Y(_181_)
  );
  OAI21X1 _564_ (
    .A(_049_),
    .B(func3_out[27]),
    .C(control[55]),
    .Y(_182_)
  );
  OAI22X1 _565_ (
    .A(control[55]),
    .B(_181_),
    .C(_182_),
    .D(_180_),
    .Y(pins[27])
  );
  NOR2X1 _566_ (
    .A(control[56]),
    .B(func2_out[28]),
    .Y(_183_)
  );
  MUX2X1 _567_ (
    .A(func1_out[28]),
    .B(func0_out[28]),
    .S(control[56]),
    .Y(_184_)
  );
  OAI21X1 _568_ (
    .A(_051_),
    .B(func3_out[28]),
    .C(control[57]),
    .Y(_185_)
  );
  OAI22X1 _569_ (
    .A(control[57]),
    .B(_184_),
    .C(_185_),
    .D(_183_),
    .Y(pins[28])
  );
  NOR2X1 _570_ (
    .A(control[58]),
    .B(func2_out[29]),
    .Y(_186_)
  );
  MUX2X1 _571_ (
    .A(func1_out[29]),
    .B(func0_out[29]),
    .S(control[58]),
    .Y(_187_)
  );
  OAI21X1 _572_ (
    .A(_053_),
    .B(func3_out[29]),
    .C(control[59]),
    .Y(_188_)
  );
  OAI22X1 _573_ (
    .A(control[59]),
    .B(_187_),
    .C(_188_),
    .D(_186_),
    .Y(pins[29])
  );
  NOR2X1 _574_ (
    .A(control[60]),
    .B(func2_out[30]),
    .Y(_189_)
  );
  MUX2X1 _575_ (
    .A(func1_out[30]),
    .B(func0_out[30]),
    .S(control[60]),
    .Y(_190_)
  );
  OAI21X1 _576_ (
    .A(_055_),
    .B(func3_out[30]),
    .C(control[61]),
    .Y(_191_)
  );
  OAI22X1 _577_ (
    .A(control[61]),
    .B(_190_),
    .C(_191_),
    .D(_189_),
    .Y(pins[30])
  );
  NOR2X1 _578_ (
    .A(control[62]),
    .B(func2_out[31]),
    .Y(_192_)
  );
  MUX2X1 _579_ (
    .A(func1_out[31]),
    .B(func0_out[31]),
    .S(control[62]),
    .Y(_193_)
  );
  OAI21X1 _580_ (
    .A(_057_),
    .B(func3_out[31]),
    .C(control[63]),
    .Y(_194_)
  );
  OAI22X1 _581_ (
    .A(control[63]),
    .B(_193_),
    .C(_194_),
    .D(_192_),
    .Y(pins[31])
  );
  XNOR2X1 _582_ (
    .A(addr[19]),
    .B(sys_w_addr[19]),
    .Y(_195_)
  );
  XNOR2X1 _583_ (
    .A(addr[13]),
    .B(sys_w_addr[13]),
    .Y(_196_)
  );
  XNOR2X1 _584_ (
    .A(addr[30]),
    .B(sys_w_addr[30]),
    .Y(_197_)
  );
  XNOR2X1 _585_ (
    .A(addr[29]),
    .B(sys_w_addr[29]),
    .Y(_198_)
  );
  NOR2X1 _586_ (
    .A(addr[22]),
    .B(sys_w_addr[22]),
    .Y(_199_)
  );
  AND2X1 _587_ (
    .A(addr[22]),
    .B(sys_w_addr[22]),
    .Y(_200_)
  );
  AND2X1 _588_ (
    .A(addr[16]),
    .B(sys_w_addr[16]),
    .Y(_201_)
  );
  NOR2X1 _589_ (
    .A(addr[16]),
    .B(sys_w_addr[16]),
    .Y(_202_)
  );
  XNOR2X1 _590_ (
    .A(addr[9]),
    .B(sys_w_addr[9]),
    .Y(_203_)
  );
  XOR2X1 _591_ (
    .A(addr[15]),
    .B(sys_w_addr[15]),
    .Y(_204_)
  );
  XOR2X1 _592_ (
    .A(addr[23]),
    .B(sys_w_addr[23]),
    .Y(_205_)
  );
  XOR2X1 _593_ (
    .A(addr[24]),
    .B(sys_w_addr[24]),
    .Y(_206_)
  );
  NOR2X1 _594_ (
    .A(_205_),
    .B(_206_),
    .Y(_207_)
  );
  NAND3X1 _595_ (
    .A(_197_),
    .B(_198_),
    .C(_207_),
    .Y(_208_)
  );
  XOR2X1 _596_ (
    .A(addr[11]),
    .B(sys_w_addr[11]),
    .Y(_209_)
  );
  XOR2X1 _597_ (
    .A(addr[1]),
    .B(sys_w_addr[1]),
    .Y(_210_)
  );
  NOR2X1 _598_ (
    .A(_209_),
    .B(_210_),
    .Y(_211_)
  );
  XNOR2X1 _599_ (
    .A(addr[5]),
    .B(sys_w_addr[5]),
    .Y(_212_)
  );
  XNOR2X1 _600_ (
    .A(addr[6]),
    .B(sys_w_addr[6]),
    .Y(_213_)
  );
  NAND3X1 _601_ (
    .A(_211_),
    .B(_212_),
    .C(_213_),
    .Y(_214_)
  );
  OR2X1 _602_ (
    .A(_208_),
    .B(_214_),
    .Y(_215_)
  );
  XOR2X1 _603_ (
    .A(addr[8]),
    .B(sys_w_addr[8]),
    .Y(_216_)
  );
  OAI22X1 _604_ (
    .A(_064_),
    .B(sys_w_addr[3]),
    .C(addr[7]),
    .D(_066_),
    .Y(_217_)
  );
  NOR2X1 _605_ (
    .A(_216_),
    .B(_217_),
    .Y(_218_)
  );
  OAI22X1 _606_ (
    .A(_070_),
    .B(sys_w_addr[20]),
    .C(_071_),
    .D(sys_w_addr[26]),
    .Y(_219_)
  );
  OAI22X1 _607_ (
    .A(addr[3]),
    .B(_065_),
    .C(addr[26]),
    .D(_072_),
    .Y(_220_)
  );
  NOR2X1 _608_ (
    .A(_219_),
    .B(_220_),
    .Y(_221_)
  );
  XNOR2X1 _609_ (
    .A(addr[4]),
    .B(sys_w_addr[4]),
    .Y(_222_)
  );
  XNOR2X1 _610_ (
    .A(addr[10]),
    .B(sys_w_addr[10]),
    .Y(_223_)
  );
  NAND2X1 _611_ (
    .A(_222_),
    .B(_223_),
    .Y(_224_)
  );
  XNOR2X1 _612_ (
    .A(addr[14]),
    .B(sys_w_addr[14]),
    .Y(_225_)
  );
  XNOR2X1 _613_ (
    .A(addr[17]),
    .B(sys_w_addr[17]),
    .Y(_226_)
  );
  NAND2X1 _614_ (
    .A(_225_),
    .B(_226_),
    .Y(_227_)
  );
  NOR2X1 _615_ (
    .A(_224_),
    .B(_227_),
    .Y(_228_)
  );
  NAND3X1 _616_ (
    .A(_218_),
    .B(_221_),
    .C(_228_),
    .Y(_229_)
  );
  NOR2X1 _617_ (
    .A(_215_),
    .B(_229_),
    .Y(_230_)
  );
  XOR2X1 _618_ (
    .A(addr[31]),
    .B(sys_w_addr[31]),
    .Y(_231_)
  );
  OAI22X1 _619_ (
    .A(addr[12]),
    .B(_067_),
    .C(_068_),
    .D(sys_w_addr[18]),
    .Y(_232_)
  );
  NOR2X1 _620_ (
    .A(_231_),
    .B(_232_),
    .Y(_233_)
  );
  XOR2X1 _621_ (
    .A(addr[27]),
    .B(sys_w_addr[27]),
    .Y(_234_)
  );
  OAI21X1 _622_ (
    .A(addr[18]),
    .B(_069_),
    .C(sys_w),
    .Y(_235_)
  );
  NOR2X1 _623_ (
    .A(_234_),
    .B(_235_),
    .Y(_236_)
  );
  OAI21X1 _624_ (
    .A(_199_),
    .B(_200_),
    .C(_195_),
    .Y(_237_)
  );
  OAI21X1 _625_ (
    .A(_201_),
    .B(_202_),
    .C(_196_),
    .Y(_238_)
  );
  NOR2X1 _626_ (
    .A(_237_),
    .B(_238_),
    .Y(_239_)
  );
  NAND3X1 _627_ (
    .A(_233_),
    .B(_236_),
    .C(_239_),
    .Y(_240_)
  );
  AOI22X1 _628_ (
    .A(addr[2]),
    .B(_063_),
    .C(addr[7]),
    .D(_066_),
    .Y(_241_)
  );
  AOI21X1 _629_ (
    .A(_070_),
    .B(sys_w_addr[20]),
    .C(_204_),
    .Y(_242_)
  );
  NAND3X1 _630_ (
    .A(_203_),
    .B(_241_),
    .C(_242_),
    .Y(_243_)
  );
  XNOR2X1 _631_ (
    .A(addr[28]),
    .B(sys_w_addr[28]),
    .Y(_244_)
  );
  AOI22X1 _632_ (
    .A(_062_),
    .B(sys_w_addr[2]),
    .C(addr[12]),
    .D(_067_),
    .Y(_245_)
  );
  XOR2X1 _633_ (
    .A(addr[25]),
    .B(sys_w_addr[25]),
    .Y(_246_)
  );
  XOR2X1 _634_ (
    .A(addr[21]),
    .B(sys_w_addr[21]),
    .Y(_247_)
  );
  NOR2X1 _635_ (
    .A(_246_),
    .B(_247_),
    .Y(_248_)
  );
  NAND3X1 _636_ (
    .A(_244_),
    .B(_245_),
    .C(_248_),
    .Y(_249_)
  );
  OR2X1 _637_ (
    .A(_243_),
    .B(_249_),
    .Y(_250_)
  );
  NOR2X1 _638_ (
    .A(_240_),
    .B(_250_),
    .Y(_251_)
  );
  NAND3X1 _639_ (
    .A(_061_),
    .B(_230_),
    .C(_251_),
    .Y(_252_)
  );
  MUX2X1 _640_ (
    .A(_060_),
    .B(_059_),
    .S(_252_),
    .Y(_000_[0])
  );
  MUX2X1 _641_ (
    .A(_074_),
    .B(_073_),
    .S(_252_),
    .Y(_000_[1])
  );
  MUX2X1 _642_ (
    .A(_076_),
    .B(_075_),
    .S(_252_),
    .Y(_000_[2])
  );
  MUX2X1 _643_ (
    .A(_078_),
    .B(_077_),
    .S(_252_),
    .Y(_000_[3])
  );
  MUX2X1 _644_ (
    .A(_080_),
    .B(_079_),
    .S(_252_),
    .Y(_000_[4])
  );
  MUX2X1 _645_ (
    .A(_082_),
    .B(_081_),
    .S(_252_),
    .Y(_000_[5])
  );
  MUX2X1 _646_ (
    .A(_084_),
    .B(_083_),
    .S(_252_),
    .Y(_000_[6])
  );
  MUX2X1 _647_ (
    .A(_086_),
    .B(_085_),
    .S(_252_),
    .Y(_000_[7])
  );
  MUX2X1 _648_ (
    .A(_003_),
    .B(_087_),
    .S(_252_),
    .Y(_000_[8])
  );
  MUX2X1 _649_ (
    .A(_004_),
    .B(_088_),
    .S(_252_),
    .Y(_000_[9])
  );
  MUX2X1 _650_ (
    .A(_005_),
    .B(_089_),
    .S(_252_),
    .Y(_000_[10])
  );
  MUX2X1 _651_ (
    .A(_006_),
    .B(_090_),
    .S(_252_),
    .Y(_000_[11])
  );
  MUX2X1 _652_ (
    .A(_007_),
    .B(_091_),
    .S(_252_),
    .Y(_000_[12])
  );
  MUX2X1 _653_ (
    .A(_008_),
    .B(_092_),
    .S(_252_),
    .Y(_000_[13])
  );
  MUX2X1 _654_ (
    .A(_009_),
    .B(_093_),
    .S(_252_),
    .Y(_000_[14])
  );
  MUX2X1 _655_ (
    .A(_010_),
    .B(_094_),
    .S(_252_),
    .Y(_000_[15])
  );
  MUX2X1 _656_ (
    .A(_011_),
    .B(_095_),
    .S(_252_),
    .Y(_000_[16])
  );
  MUX2X1 _657_ (
    .A(_012_),
    .B(_096_),
    .S(_252_),
    .Y(_000_[17])
  );
  MUX2X1 _658_ (
    .A(_013_),
    .B(_097_),
    .S(_252_),
    .Y(_000_[18])
  );
  MUX2X1 _659_ (
    .A(_014_),
    .B(_098_),
    .S(_252_),
    .Y(_000_[19])
  );
  MUX2X1 _660_ (
    .A(_015_),
    .B(_099_),
    .S(_252_),
    .Y(_000_[20])
  );
  MUX2X1 _661_ (
    .A(_016_),
    .B(_100_),
    .S(_252_),
    .Y(_000_[21])
  );
  MUX2X1 _662_ (
    .A(_017_),
    .B(_101_),
    .S(_252_),
    .Y(_000_[22])
  );
  MUX2X1 _663_ (
    .A(_018_),
    .B(_102_),
    .S(_252_),
    .Y(_000_[23])
  );
  MUX2X1 _664_ (
    .A(_019_),
    .B(_103_),
    .S(_252_),
    .Y(_000_[24])
  );
  MUX2X1 _665_ (
    .A(_020_),
    .B(_104_),
    .S(_252_),
    .Y(_000_[25])
  );
  MUX2X1 _666_ (
    .A(_021_),
    .B(_105_),
    .S(_252_),
    .Y(_000_[26])
  );
  MUX2X1 _667_ (
    .A(_022_),
    .B(_106_),
    .S(_252_),
    .Y(_000_[27])
  );
  MUX2X1 _668_ (
    .A(_023_),
    .B(_107_),
    .S(_252_),
    .Y(_000_[28])
  );
  MUX2X1 _669_ (
    .A(_024_),
    .B(_108_),
    .S(_252_),
    .Y(_000_[29])
  );
  MUX2X1 _670_ (
    .A(_025_),
    .B(_109_),
    .S(_252_),
    .Y(_000_[30])
  );
  MUX2X1 _671_ (
    .A(_026_),
    .B(_110_),
    .S(_252_),
    .Y(_000_[31])
  );
  NAND3X1 _672_ (
    .A(sys_w_addr[0]),
    .B(_230_),
    .C(_251_),
    .Y(_280_)
  );
  MUX2X1 _673_ (
    .A(_027_),
    .B(_059_),
    .S(_280_),
    .Y(_000_[32])
  );
  MUX2X1 _674_ (
    .A(_028_),
    .B(_073_),
    .S(_280_),
    .Y(_000_[33])
  );
  MUX2X1 _675_ (
    .A(_029_),
    .B(_075_),
    .S(_280_),
    .Y(_000_[34])
  );
  MUX2X1 _676_ (
    .A(_030_),
    .B(_077_),
    .S(_280_),
    .Y(_000_[35])
  );
  MUX2X1 _677_ (
    .A(_031_),
    .B(_079_),
    .S(_280_),
    .Y(_000_[36])
  );
  MUX2X1 _678_ (
    .A(_032_),
    .B(_081_),
    .S(_280_),
    .Y(_000_[37])
  );
  MUX2X1 _679_ (
    .A(_033_),
    .B(_083_),
    .S(_280_),
    .Y(_000_[38])
  );
  MUX2X1 _680_ (
    .A(_034_),
    .B(_085_),
    .S(_280_),
    .Y(_000_[39])
  );
  MUX2X1 _681_ (
    .A(_035_),
    .B(_087_),
    .S(_280_),
    .Y(_000_[40])
  );
  MUX2X1 _682_ (
    .A(_036_),
    .B(_088_),
    .S(_280_),
    .Y(_000_[41])
  );
  MUX2X1 _683_ (
    .A(_037_),
    .B(_089_),
    .S(_280_),
    .Y(_000_[42])
  );
  MUX2X1 _684_ (
    .A(_038_),
    .B(_090_),
    .S(_280_),
    .Y(_000_[43])
  );
  MUX2X1 _685_ (
    .A(_039_),
    .B(_091_),
    .S(_280_),
    .Y(_000_[44])
  );
  MUX2X1 _686_ (
    .A(_040_),
    .B(_092_),
    .S(_280_),
    .Y(_000_[45])
  );
  MUX2X1 _687_ (
    .A(_041_),
    .B(_093_),
    .S(_280_),
    .Y(_000_[46])
  );
  MUX2X1 _688_ (
    .A(_042_),
    .B(_094_),
    .S(_280_),
    .Y(_000_[47])
  );
  MUX2X1 _689_ (
    .A(_043_),
    .B(_095_),
    .S(_280_),
    .Y(_000_[48])
  );
  MUX2X1 _690_ (
    .A(_044_),
    .B(_096_),
    .S(_280_),
    .Y(_000_[49])
  );
  MUX2X1 _691_ (
    .A(_045_),
    .B(_097_),
    .S(_280_),
    .Y(_000_[50])
  );
  MUX2X1 _692_ (
    .A(_046_),
    .B(_098_),
    .S(_280_),
    .Y(_000_[51])
  );
  MUX2X1 _693_ (
    .A(_047_),
    .B(_099_),
    .S(_280_),
    .Y(_000_[52])
  );
  MUX2X1 _694_ (
    .A(_048_),
    .B(_100_),
    .S(_280_),
    .Y(_000_[53])
  );
  MUX2X1 _695_ (
    .A(_049_),
    .B(_101_),
    .S(_280_),
    .Y(_000_[54])
  );
  MUX2X1 _696_ (
    .A(_050_),
    .B(_102_),
    .S(_280_),
    .Y(_000_[55])
  );
  MUX2X1 _697_ (
    .A(_051_),
    .B(_103_),
    .S(_280_),
    .Y(_000_[56])
  );
  MUX2X1 _698_ (
    .A(_052_),
    .B(_104_),
    .S(_280_),
    .Y(_000_[57])
  );
  MUX2X1 _699_ (
    .A(_053_),
    .B(_105_),
    .S(_280_),
    .Y(_000_[58])
  );
  MUX2X1 _700_ (
    .A(_054_),
    .B(_106_),
    .S(_280_),
    .Y(_000_[59])
  );
  MUX2X1 _701_ (
    .A(_055_),
    .B(_107_),
    .S(_280_),
    .Y(_000_[60])
  );
  MUX2X1 _702_ (
    .A(_056_),
    .B(_108_),
    .S(_280_),
    .Y(_000_[61])
  );
  MUX2X1 _703_ (
    .A(_057_),
    .B(_109_),
    .S(_280_),
    .Y(_000_[62])
  );
  MUX2X1 _704_ (
    .A(_058_),
    .B(_110_),
    .S(_280_),
    .Y(_000_[63])
  );
  NAND2X1 _705_ (
    .A(control[32]),
    .B(sys_r_addr[0]),
    .Y(_314_)
  );
  OAI21X1 _706_ (
    .A(_060_),
    .B(sys_r_addr[0]),
    .C(_314_),
    .Y(_001_[0])
  );
  NAND2X1 _707_ (
    .A(control[33]),
    .B(sys_r_addr[0]),
    .Y(_317_)
  );
  OAI21X1 _708_ (
    .A(_074_),
    .B(sys_r_addr[0]),
    .C(_317_),
    .Y(_001_[1])
  );
  NAND2X1 _709_ (
    .A(control[34]),
    .B(sys_r_addr[0]),
    .Y(_319_)
  );
  OAI21X1 _710_ (
    .A(_076_),
    .B(sys_r_addr[0]),
    .C(_319_),
    .Y(_001_[2])
  );
  NAND2X1 _711_ (
    .A(control[35]),
    .B(sys_r_addr[0]),
    .Y(_320_)
  );
  OAI21X1 _712_ (
    .A(_078_),
    .B(sys_r_addr[0]),
    .C(_320_),
    .Y(_001_[3])
  );
  NAND2X1 _713_ (
    .A(control[36]),
    .B(sys_r_addr[0]),
    .Y(_321_)
  );
  OAI21X1 _714_ (
    .A(_080_),
    .B(sys_r_addr[0]),
    .C(_321_),
    .Y(_001_[4])
  );
  NAND2X1 _715_ (
    .A(control[37]),
    .B(sys_r_addr[0]),
    .Y(_322_)
  );
  OAI21X1 _716_ (
    .A(_082_),
    .B(sys_r_addr[0]),
    .C(_322_),
    .Y(_001_[5])
  );
  NAND2X1 _717_ (
    .A(control[38]),
    .B(sys_r_addr[0]),
    .Y(_323_)
  );
  OAI21X1 _718_ (
    .A(_084_),
    .B(sys_r_addr[0]),
    .C(_323_),
    .Y(_001_[6])
  );
  NAND2X1 _719_ (
    .A(control[39]),
    .B(sys_r_addr[0]),
    .Y(_324_)
  );
  OAI21X1 _720_ (
    .A(_086_),
    .B(sys_r_addr[0]),
    .C(_324_),
    .Y(_001_[7])
  );
  NAND2X1 _721_ (
    .A(control[40]),
    .B(sys_r_addr[0]),
    .Y(_325_)
  );
  OAI21X1 _722_ (
    .A(_003_),
    .B(sys_r_addr[0]),
    .C(_325_),
    .Y(_001_[8])
  );
  NAND2X1 _723_ (
    .A(control[41]),
    .B(sys_r_addr[0]),
    .Y(_326_)
  );
  OAI21X1 _724_ (
    .A(_004_),
    .B(sys_r_addr[0]),
    .C(_326_),
    .Y(_001_[9])
  );
  NAND2X1 _725_ (
    .A(control[42]),
    .B(sys_r_addr[0]),
    .Y(_327_)
  );
  OAI21X1 _726_ (
    .A(_005_),
    .B(sys_r_addr[0]),
    .C(_327_),
    .Y(_001_[10])
  );
  NAND2X1 _727_ (
    .A(control[43]),
    .B(sys_r_addr[0]),
    .Y(_328_)
  );
  OAI21X1 _728_ (
    .A(_006_),
    .B(sys_r_addr[0]),
    .C(_328_),
    .Y(_001_[11])
  );
  NAND2X1 _729_ (
    .A(control[44]),
    .B(sys_r_addr[0]),
    .Y(_329_)
  );
  OAI21X1 _730_ (
    .A(_007_),
    .B(sys_r_addr[0]),
    .C(_329_),
    .Y(_001_[12])
  );
  NAND2X1 _731_ (
    .A(control[45]),
    .B(sys_r_addr[0]),
    .Y(_330_)
  );
  OAI21X1 _732_ (
    .A(_008_),
    .B(sys_r_addr[0]),
    .C(_330_),
    .Y(_001_[13])
  );
  NAND2X1 _733_ (
    .A(control[46]),
    .B(sys_r_addr[0]),
    .Y(_331_)
  );
  OAI21X1 _734_ (
    .A(_009_),
    .B(sys_r_addr[0]),
    .C(_331_),
    .Y(_001_[14])
  );
  NAND2X1 _735_ (
    .A(control[47]),
    .B(sys_r_addr[0]),
    .Y(_332_)
  );
  OAI21X1 _736_ (
    .A(_010_),
    .B(sys_r_addr[0]),
    .C(_332_),
    .Y(_001_[15])
  );
  NAND2X1 _737_ (
    .A(control[48]),
    .B(sys_r_addr[0]),
    .Y(_333_)
  );
  OAI21X1 _738_ (
    .A(_011_),
    .B(sys_r_addr[0]),
    .C(_333_),
    .Y(_001_[16])
  );
  NAND2X1 _739_ (
    .A(control[49]),
    .B(sys_r_addr[0]),
    .Y(_334_)
  );
  OAI21X1 _740_ (
    .A(_012_),
    .B(sys_r_addr[0]),
    .C(_334_),
    .Y(_001_[17])
  );
  NAND2X1 _741_ (
    .A(control[50]),
    .B(sys_r_addr[0]),
    .Y(_335_)
  );
  OAI21X1 _742_ (
    .A(_013_),
    .B(sys_r_addr[0]),
    .C(_335_),
    .Y(_001_[18])
  );
  NAND2X1 _743_ (
    .A(control[51]),
    .B(sys_r_addr[0]),
    .Y(_336_)
  );
  OAI21X1 _744_ (
    .A(_014_),
    .B(sys_r_addr[0]),
    .C(_336_),
    .Y(_001_[19])
  );
  NAND2X1 _745_ (
    .A(control[52]),
    .B(sys_r_addr[0]),
    .Y(_337_)
  );
  OAI21X1 _746_ (
    .A(_015_),
    .B(sys_r_addr[0]),
    .C(_337_),
    .Y(_001_[20])
  );
  NAND2X1 _747_ (
    .A(control[53]),
    .B(sys_r_addr[0]),
    .Y(_338_)
  );
  OAI21X1 _748_ (
    .A(_016_),
    .B(sys_r_addr[0]),
    .C(_338_),
    .Y(_001_[21])
  );
  NAND2X1 _749_ (
    .A(control[54]),
    .B(sys_r_addr[0]),
    .Y(_339_)
  );
  OAI21X1 _750_ (
    .A(_017_),
    .B(sys_r_addr[0]),
    .C(_339_),
    .Y(_001_[22])
  );
  NAND2X1 _751_ (
    .A(control[55]),
    .B(sys_r_addr[0]),
    .Y(_340_)
  );
  OAI21X1 _752_ (
    .A(_018_),
    .B(sys_r_addr[0]),
    .C(_340_),
    .Y(_001_[23])
  );
  NAND2X1 _753_ (
    .A(control[56]),
    .B(sys_r_addr[0]),
    .Y(_341_)
  );
  OAI21X1 _754_ (
    .A(_019_),
    .B(sys_r_addr[0]),
    .C(_341_),
    .Y(_001_[24])
  );
  NAND2X1 _755_ (
    .A(control[57]),
    .B(sys_r_addr[0]),
    .Y(_342_)
  );
  OAI21X1 _756_ (
    .A(_020_),
    .B(sys_r_addr[0]),
    .C(_342_),
    .Y(_001_[25])
  );
  NAND2X1 _757_ (
    .A(control[58]),
    .B(sys_r_addr[0]),
    .Y(_343_)
  );
  OAI21X1 _758_ (
    .A(_021_),
    .B(sys_r_addr[0]),
    .C(_343_),
    .Y(_001_[26])
  );
  NAND2X1 _759_ (
    .A(control[59]),
    .B(sys_r_addr[0]),
    .Y(_344_)
  );
  OAI21X1 _760_ (
    .A(_022_),
    .B(sys_r_addr[0]),
    .C(_344_),
    .Y(_001_[27])
  );
  NAND2X1 _761_ (
    .A(control[60]),
    .B(sys_r_addr[0]),
    .Y(_345_)
  );
  OAI21X1 _762_ (
    .A(_023_),
    .B(sys_r_addr[0]),
    .C(_345_),
    .Y(_001_[28])
  );
  NAND2X1 _763_ (
    .A(control[61]),
    .B(sys_r_addr[0]),
    .Y(_346_)
  );
  OAI21X1 _764_ (
    .A(_024_),
    .B(sys_r_addr[0]),
    .C(_346_),
    .Y(_001_[29])
  );
  NAND2X1 _765_ (
    .A(control[62]),
    .B(sys_r_addr[0]),
    .Y(_347_)
  );
  OAI21X1 _766_ (
    .A(_025_),
    .B(sys_r_addr[0]),
    .C(_347_),
    .Y(_001_[30])
  );
  NAND2X1 _767_ (
    .A(control[63]),
    .B(sys_r_addr[0]),
    .Y(_348_)
  );
  OAI21X1 _768_ (
    .A(_026_),
    .B(sys_r_addr[0]),
    .C(_348_),
    .Y(_001_[31])
  );
  NOR2X1 _769_ (
    .A(control[0]),
    .B(func2_out[0]),
    .Y(_349_)
  );
  MUX2X1 _770_ (
    .A(func1_out[0]),
    .B(func0_out[0]),
    .S(control[0]),
    .Y(_350_)
  );
  OAI21X1 _771_ (
    .A(_060_),
    .B(func3_out[0]),
    .C(control[1]),
    .Y(_351_)
  );
  OAI22X1 _772_ (
    .A(control[1]),
    .B(_350_),
    .C(_351_),
    .D(_349_),
    .Y(pins[0])
  );
  NOR2X1 _773_ (
    .A(control[2]),
    .B(func2_out[1]),
    .Y(_352_)
  );
  MUX2X1 _774_ (
    .A(func1_out[1]),
    .B(func0_out[1]),
    .S(control[2]),
    .Y(_353_)
  );
  OAI21X1 _775_ (
    .A(_076_),
    .B(func3_out[1]),
    .C(control[3]),
    .Y(_354_)
  );
  OAI22X1 _776_ (
    .A(control[3]),
    .B(_353_),
    .C(_354_),
    .D(_352_),
    .Y(pins[1])
  );
  NOR2X1 _777_ (
    .A(control[4]),
    .B(func2_out[2]),
    .Y(_355_)
  );
  MUX2X1 _778_ (
    .A(func1_out[2]),
    .B(func0_out[2]),
    .S(control[4]),
    .Y(_356_)
  );
  OAI21X1 _779_ (
    .A(_080_),
    .B(func3_out[2]),
    .C(control[5]),
    .Y(_357_)
  );
  OAI22X1 _780_ (
    .A(control[5]),
    .B(_356_),
    .C(_357_),
    .D(_355_),
    .Y(pins[2])
  );
  NOR2X1 _781_ (
    .A(control[6]),
    .B(func2_out[3]),
    .Y(_358_)
  );
  MUX2X1 _782_ (
    .A(func1_out[3]),
    .B(func0_out[3]),
    .S(control[6]),
    .Y(_359_)
  );
  OAI21X1 _783_ (
    .A(_084_),
    .B(func3_out[3]),
    .C(control[7]),
    .Y(_360_)
  );
  OAI22X1 _784_ (
    .A(control[7]),
    .B(_359_),
    .C(_360_),
    .D(_358_),
    .Y(pins[3])
  );
  INVX1 _785_ (
    .A(rst),
    .Y(_253_)
  );
  INVX1 _786_ (
    .A(rst),
    .Y(_254_)
  );
  INVX1 _787_ (
    .A(rst),
    .Y(_255_)
  );
  INVX1 _788_ (
    .A(rst),
    .Y(_256_)
  );
  INVX1 _789_ (
    .A(rst),
    .Y(_257_)
  );
  INVX1 _790_ (
    .A(rst),
    .Y(_258_)
  );
  INVX1 _791_ (
    .A(rst),
    .Y(_259_)
  );
  INVX1 _792_ (
    .A(rst),
    .Y(_260_)
  );
  INVX1 _793_ (
    .A(rst),
    .Y(_261_)
  );
  INVX1 _794_ (
    .A(rst),
    .Y(_262_)
  );
  INVX1 _795_ (
    .A(rst),
    .Y(_263_)
  );
  INVX1 _796_ (
    .A(rst),
    .Y(_264_)
  );
  INVX1 _797_ (
    .A(rst),
    .Y(_265_)
  );
  INVX1 _798_ (
    .A(rst),
    .Y(_266_)
  );
  INVX1 _799_ (
    .A(rst),
    .Y(_267_)
  );
  INVX1 _800_ (
    .A(rst),
    .Y(_268_)
  );
  INVX1 _801_ (
    .A(rst),
    .Y(_269_)
  );
  INVX1 _802_ (
    .A(rst),
    .Y(_270_)
  );
  INVX1 _803_ (
    .A(rst),
    .Y(_271_)
  );
  INVX1 _804_ (
    .A(rst),
    .Y(_272_)
  );
  INVX1 _805_ (
    .A(rst),
    .Y(_273_)
  );
  INVX1 _806_ (
    .A(rst),
    .Y(_274_)
  );
  INVX1 _807_ (
    .A(rst),
    .Y(_275_)
  );
  INVX1 _808_ (
    .A(rst),
    .Y(_276_)
  );
  INVX1 _809_ (
    .A(rst),
    .Y(_277_)
  );
  INVX1 _810_ (
    .A(rst),
    .Y(_278_)
  );
  INVX1 _811_ (
    .A(rst),
    .Y(_279_)
  );
  INVX1 _812_ (
    .A(rst),
    .Y(_281_)
  );
  INVX1 _813_ (
    .A(rst),
    .Y(_282_)
  );
  INVX1 _814_ (
    .A(rst),
    .Y(_283_)
  );
  INVX1 _815_ (
    .A(rst),
    .Y(_284_)
  );
  INVX1 _816_ (
    .A(rst),
    .Y(_285_)
  );
  INVX1 _817_ (
    .A(rst),
    .Y(_286_)
  );
  INVX1 _818_ (
    .A(rst),
    .Y(_287_)
  );
  INVX1 _819_ (
    .A(rst),
    .Y(_288_)
  );
  INVX1 _820_ (
    .A(rst),
    .Y(_289_)
  );
  INVX1 _821_ (
    .A(rst),
    .Y(_290_)
  );
  INVX1 _822_ (
    .A(rst),
    .Y(_291_)
  );
  INVX1 _823_ (
    .A(rst),
    .Y(_292_)
  );
  INVX1 _824_ (
    .A(rst),
    .Y(_293_)
  );
  INVX1 _825_ (
    .A(rst),
    .Y(_294_)
  );
  INVX1 _826_ (
    .A(rst),
    .Y(_295_)
  );
  INVX1 _827_ (
    .A(rst),
    .Y(_296_)
  );
  INVX1 _828_ (
    .A(rst),
    .Y(_297_)
  );
  INVX1 _829_ (
    .A(rst),
    .Y(_298_)
  );
  INVX1 _830_ (
    .A(rst),
    .Y(_299_)
  );
  INVX1 _831_ (
    .A(rst),
    .Y(_300_)
  );
  INVX1 _832_ (
    .A(rst),
    .Y(_301_)
  );
  INVX1 _833_ (
    .A(rst),
    .Y(_302_)
  );
  INVX1 _834_ (
    .A(rst),
    .Y(_303_)
  );
  INVX1 _835_ (
    .A(rst),
    .Y(_304_)
  );
  INVX1 _836_ (
    .A(rst),
    .Y(_305_)
  );
  INVX1 _837_ (
    .A(rst),
    .Y(_306_)
  );
  INVX1 _838_ (
    .A(rst),
    .Y(_307_)
  );
  INVX1 _839_ (
    .A(rst),
    .Y(_308_)
  );
  INVX1 _840_ (
    .A(rst),
    .Y(_309_)
  );
  INVX1 _841_ (
    .A(rst),
    .Y(_310_)
  );
  INVX1 _842_ (
    .A(rst),
    .Y(_311_)
  );
  INVX1 _843_ (
    .A(rst),
    .Y(_312_)
  );
  INVX1 _844_ (
    .A(rst),
    .Y(_313_)
  );
  INVX1 _845_ (
    .A(rst),
    .Y(_315_)
  );
  INVX1 _846_ (
    .A(rst),
    .Y(_316_)
  );
  INVX1 _847_ (
    .A(rst),
    .Y(_318_)
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _848_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(sys_r_line[0])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _849_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(sys_r_line[1])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _850_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(sys_r_line[2])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _851_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(sys_r_line[3])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _852_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(sys_r_line[4])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _853_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(sys_r_line[5])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _854_ (
    .CLK(clk),
    .D(_001_[6]),
    .Q(sys_r_line[6])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _855_ (
    .CLK(clk),
    .D(_001_[7]),
    .Q(sys_r_line[7])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _856_ (
    .CLK(clk),
    .D(_001_[8]),
    .Q(sys_r_line[8])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _857_ (
    .CLK(clk),
    .D(_001_[9]),
    .Q(sys_r_line[9])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _858_ (
    .CLK(clk),
    .D(_001_[10]),
    .Q(sys_r_line[10])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _859_ (
    .CLK(clk),
    .D(_001_[11]),
    .Q(sys_r_line[11])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _860_ (
    .CLK(clk),
    .D(_001_[12]),
    .Q(sys_r_line[12])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _861_ (
    .CLK(clk),
    .D(_001_[13]),
    .Q(sys_r_line[13])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _862_ (
    .CLK(clk),
    .D(_001_[14]),
    .Q(sys_r_line[14])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _863_ (
    .CLK(clk),
    .D(_001_[15]),
    .Q(sys_r_line[15])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _864_ (
    .CLK(clk),
    .D(_001_[16]),
    .Q(sys_r_line[16])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _865_ (
    .CLK(clk),
    .D(_001_[17]),
    .Q(sys_r_line[17])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _866_ (
    .CLK(clk),
    .D(_001_[18]),
    .Q(sys_r_line[18])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _867_ (
    .CLK(clk),
    .D(_001_[19]),
    .Q(sys_r_line[19])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _868_ (
    .CLK(clk),
    .D(_001_[20]),
    .Q(sys_r_line[20])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _869_ (
    .CLK(clk),
    .D(_001_[21]),
    .Q(sys_r_line[21])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _870_ (
    .CLK(clk),
    .D(_001_[22]),
    .Q(sys_r_line[22])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _871_ (
    .CLK(clk),
    .D(_001_[23]),
    .Q(sys_r_line[23])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _872_ (
    .CLK(clk),
    .D(_001_[24]),
    .Q(sys_r_line[24])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _873_ (
    .CLK(clk),
    .D(_001_[25]),
    .Q(sys_r_line[25])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _874_ (
    .CLK(clk),
    .D(_001_[26]),
    .Q(sys_r_line[26])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _875_ (
    .CLK(clk),
    .D(_001_[27]),
    .Q(sys_r_line[27])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _876_ (
    .CLK(clk),
    .D(_001_[28]),
    .Q(sys_r_line[28])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _877_ (
    .CLK(clk),
    .D(_001_[29]),
    .Q(sys_r_line[29])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _878_ (
    .CLK(clk),
    .D(_001_[30]),
    .Q(sys_r_line[30])
  );
  (* src = "gpio_mux.v:58" *)
  DFFPOSX1 _879_ (
    .CLK(clk),
    .D(_001_[31]),
    .Q(sys_r_line[31])
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _880_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(control[0]),
    .R(_253_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _881_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(control[1]),
    .R(_254_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _882_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(control[2]),
    .R(_255_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _883_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(control[3]),
    .R(_256_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _884_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(control[4]),
    .R(_257_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _885_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(control[5]),
    .R(_258_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _886_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(control[6]),
    .R(_259_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _887_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(control[7]),
    .R(_260_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _888_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(control[8]),
    .R(_261_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _889_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(control[9]),
    .R(_262_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _890_ (
    .CLK(clk),
    .D(_000_[10]),
    .Q(control[10]),
    .R(_263_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _891_ (
    .CLK(clk),
    .D(_000_[11]),
    .Q(control[11]),
    .R(_264_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _892_ (
    .CLK(clk),
    .D(_000_[12]),
    .Q(control[12]),
    .R(_265_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _893_ (
    .CLK(clk),
    .D(_000_[13]),
    .Q(control[13]),
    .R(_266_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _894_ (
    .CLK(clk),
    .D(_000_[14]),
    .Q(control[14]),
    .R(_267_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _895_ (
    .CLK(clk),
    .D(_000_[15]),
    .Q(control[15]),
    .R(_268_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _896_ (
    .CLK(clk),
    .D(_000_[16]),
    .Q(control[16]),
    .R(_269_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _897_ (
    .CLK(clk),
    .D(_000_[17]),
    .Q(control[17]),
    .R(_270_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _898_ (
    .CLK(clk),
    .D(_000_[18]),
    .Q(control[18]),
    .R(_271_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _899_ (
    .CLK(clk),
    .D(_000_[19]),
    .Q(control[19]),
    .R(_272_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _900_ (
    .CLK(clk),
    .D(_000_[20]),
    .Q(control[20]),
    .R(_273_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _901_ (
    .CLK(clk),
    .D(_000_[21]),
    .Q(control[21]),
    .R(_274_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _902_ (
    .CLK(clk),
    .D(_000_[22]),
    .Q(control[22]),
    .R(_275_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _903_ (
    .CLK(clk),
    .D(_000_[23]),
    .Q(control[23]),
    .R(_276_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _904_ (
    .CLK(clk),
    .D(_000_[24]),
    .Q(control[24]),
    .R(_277_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _905_ (
    .CLK(clk),
    .D(_000_[25]),
    .Q(control[25]),
    .R(_278_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _906_ (
    .CLK(clk),
    .D(_000_[26]),
    .Q(control[26]),
    .R(_279_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _907_ (
    .CLK(clk),
    .D(_000_[27]),
    .Q(control[27]),
    .R(_281_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _908_ (
    .CLK(clk),
    .D(_000_[28]),
    .Q(control[28]),
    .R(_282_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _909_ (
    .CLK(clk),
    .D(_000_[29]),
    .Q(control[29]),
    .R(_283_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _910_ (
    .CLK(clk),
    .D(_000_[30]),
    .Q(control[30]),
    .R(_284_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _911_ (
    .CLK(clk),
    .D(_000_[31]),
    .Q(control[31]),
    .R(_285_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _912_ (
    .CLK(clk),
    .D(_000_[32]),
    .Q(control[32]),
    .R(_286_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _913_ (
    .CLK(clk),
    .D(_000_[33]),
    .Q(control[33]),
    .R(_287_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _914_ (
    .CLK(clk),
    .D(_000_[34]),
    .Q(control[34]),
    .R(_288_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _915_ (
    .CLK(clk),
    .D(_000_[35]),
    .Q(control[35]),
    .R(_289_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _916_ (
    .CLK(clk),
    .D(_000_[36]),
    .Q(control[36]),
    .R(_290_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _917_ (
    .CLK(clk),
    .D(_000_[37]),
    .Q(control[37]),
    .R(_291_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _918_ (
    .CLK(clk),
    .D(_000_[38]),
    .Q(control[38]),
    .R(_292_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _919_ (
    .CLK(clk),
    .D(_000_[39]),
    .Q(control[39]),
    .R(_293_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _920_ (
    .CLK(clk),
    .D(_000_[40]),
    .Q(control[40]),
    .R(_294_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _921_ (
    .CLK(clk),
    .D(_000_[41]),
    .Q(control[41]),
    .R(_295_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _922_ (
    .CLK(clk),
    .D(_000_[42]),
    .Q(control[42]),
    .R(_296_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _923_ (
    .CLK(clk),
    .D(_000_[43]),
    .Q(control[43]),
    .R(_297_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _924_ (
    .CLK(clk),
    .D(_000_[44]),
    .Q(control[44]),
    .R(_298_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _925_ (
    .CLK(clk),
    .D(_000_[45]),
    .Q(control[45]),
    .R(_299_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _926_ (
    .CLK(clk),
    .D(_000_[46]),
    .Q(control[46]),
    .R(_300_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _927_ (
    .CLK(clk),
    .D(_000_[47]),
    .Q(control[47]),
    .R(_301_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _928_ (
    .CLK(clk),
    .D(_000_[48]),
    .Q(control[48]),
    .R(_302_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _929_ (
    .CLK(clk),
    .D(_000_[49]),
    .Q(control[49]),
    .R(_303_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _930_ (
    .CLK(clk),
    .D(_000_[50]),
    .Q(control[50]),
    .R(_304_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _931_ (
    .CLK(clk),
    .D(_000_[51]),
    .Q(control[51]),
    .R(_305_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _932_ (
    .CLK(clk),
    .D(_000_[52]),
    .Q(control[52]),
    .R(_306_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _933_ (
    .CLK(clk),
    .D(_000_[53]),
    .Q(control[53]),
    .R(_307_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _934_ (
    .CLK(clk),
    .D(_000_[54]),
    .Q(control[54]),
    .R(_308_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _935_ (
    .CLK(clk),
    .D(_000_[55]),
    .Q(control[55]),
    .R(_309_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _936_ (
    .CLK(clk),
    .D(_000_[56]),
    .Q(control[56]),
    .R(_310_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _937_ (
    .CLK(clk),
    .D(_000_[57]),
    .Q(control[57]),
    .R(_311_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _938_ (
    .CLK(clk),
    .D(_000_[58]),
    .Q(control[58]),
    .R(_312_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _939_ (
    .CLK(clk),
    .D(_000_[59]),
    .Q(control[59]),
    .R(_313_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _940_ (
    .CLK(clk),
    .D(_000_[60]),
    .Q(control[60]),
    .R(_315_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _941_ (
    .CLK(clk),
    .D(_000_[61]),
    .Q(control[61]),
    .R(_316_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _942_ (
    .CLK(clk),
    .D(_000_[62]),
    .Q(control[62]),
    .R(_318_),
    .S(1'h1)
  );
  (* src = "gpio_mux.v:58" *)
  DFFSR _943_ (
    .CLK(clk),
    .D(_000_[63]),
    .Q(control[63]),
    .R(_002_),
    .S(1'h1)
  );
  assign func0_in = pins;
  assign func1_in = pins;
  assign func2_in = pins;
  assign func3_in = pins;
  assign \pin_mux[0].pin_control  = control[1:0];
  assign \pin_mux[0].pin_out  = pins[0];
  assign \pin_mux[10].pin_control  = control[21:20];
  assign \pin_mux[10].pin_out  = pins[10];
  assign \pin_mux[11].pin_control  = control[23:22];
  assign \pin_mux[11].pin_out  = pins[11];
  assign \pin_mux[12].pin_control  = control[25:24];
  assign \pin_mux[12].pin_out  = pins[12];
  assign \pin_mux[13].pin_control  = control[27:26];
  assign \pin_mux[13].pin_out  = pins[13];
  assign \pin_mux[14].pin_control  = control[29:28];
  assign \pin_mux[14].pin_out  = pins[14];
  assign \pin_mux[15].pin_control  = control[31:30];
  assign \pin_mux[15].pin_out  = pins[15];
  assign \pin_mux[16].pin_control  = control[33:32];
  assign \pin_mux[16].pin_out  = pins[16];
  assign \pin_mux[17].pin_control  = control[35:34];
  assign \pin_mux[17].pin_out  = pins[17];
  assign \pin_mux[18].pin_control  = control[37:36];
  assign \pin_mux[18].pin_out  = pins[18];
  assign \pin_mux[19].pin_control  = control[39:38];
  assign \pin_mux[19].pin_out  = pins[19];
  assign \pin_mux[1].pin_control  = control[3:2];
  assign \pin_mux[1].pin_out  = pins[1];
  assign \pin_mux[20].pin_control  = control[41:40];
  assign \pin_mux[20].pin_out  = pins[20];
  assign \pin_mux[21].pin_control  = control[43:42];
  assign \pin_mux[21].pin_out  = pins[21];
  assign \pin_mux[22].pin_control  = control[45:44];
  assign \pin_mux[22].pin_out  = pins[22];
  assign \pin_mux[23].pin_control  = control[47:46];
  assign \pin_mux[23].pin_out  = pins[23];
  assign \pin_mux[24].pin_control  = control[49:48];
  assign \pin_mux[24].pin_out  = pins[24];
  assign \pin_mux[25].pin_control  = control[51:50];
  assign \pin_mux[25].pin_out  = pins[25];
  assign \pin_mux[26].pin_control  = control[53:52];
  assign \pin_mux[26].pin_out  = pins[26];
  assign \pin_mux[27].pin_control  = control[55:54];
  assign \pin_mux[27].pin_out  = pins[27];
  assign \pin_mux[28].pin_control  = control[57:56];
  assign \pin_mux[28].pin_out  = pins[28];
  assign \pin_mux[29].pin_control  = control[59:58];
  assign \pin_mux[29].pin_out  = pins[29];
  assign \pin_mux[2].pin_control  = control[5:4];
  assign \pin_mux[2].pin_out  = pins[2];
  assign \pin_mux[30].pin_control  = control[61:60];
  assign \pin_mux[30].pin_out  = pins[30];
  assign \pin_mux[31].pin_control  = control[63:62];
  assign \pin_mux[31].pin_out  = pins[31];
  assign \pin_mux[3].pin_control  = control[7:6];
  assign \pin_mux[3].pin_out  = pins[3];
  assign \pin_mux[4].pin_control  = control[9:8];
  assign \pin_mux[4].pin_out  = pins[4];
  assign \pin_mux[5].pin_control  = control[11:10];
  assign \pin_mux[5].pin_out  = pins[5];
  assign \pin_mux[6].pin_control  = control[13:12];
  assign \pin_mux[6].pin_out  = pins[6];
  assign \pin_mux[7].pin_control  = control[15:14];
  assign \pin_mux[7].pin_out  = pins[7];
  assign \pin_mux[8].pin_control  = control[17:16];
  assign \pin_mux[8].pin_out  = pins[8];
  assign \pin_mux[9].pin_control  = control[19:18];
  assign \pin_mux[9].pin_out  = pins[9];
endmodule
