/* Generated by Yosys 0.7+307 (git sha1 7d41c5e1, gcc 7.2.0-3ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "insn_decoder_new.v:4" *)
module reg_hazard_checker(ex_hazard, mem_hazard, reg_hazard, jmp_hazard, ex_r1_a, ex_r2_a, ex_r_op, ex_proceed, mem_r1_a, mem_r2_a, mem_r_op, mem_proceed, reg_r1_a, reg_r2_a, reg_write, dec_r1_addr, dec_r2_addr, dec_r_read);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  (* src = "insn_decoder_new.v:23" *)
  input [4:0] dec_r1_addr;
  (* src = "insn_decoder_new.v:26" *)
  wire dec_r1_read_comp;
  (* src = "insn_decoder_new.v:23" *)
  input [4:0] dec_r2_addr;
  (* src = "insn_decoder_new.v:27" *)
  wire dec_r2_read_comp;
  (* src = "insn_decoder_new.v:24" *)
  input [1:0] dec_r_read;
  (* src = "insn_decoder_new.v:7" *)
  output ex_hazard;
  (* src = "insn_decoder_new.v:14" *)
  input ex_proceed;
  (* src = "insn_decoder_new.v:12" *)
  input [4:0] ex_r1_a;
  (* src = "insn_decoder_new.v:12" *)
  input [4:0] ex_r2_a;
  (* src = "insn_decoder_new.v:13" *)
  input [3:0] ex_r_op;
  (* src = "insn_decoder_new.v:10" *)
  output jmp_hazard;
  (* src = "insn_decoder_new.v:8" *)
  output mem_hazard;
  (* src = "insn_decoder_new.v:18" *)
  input mem_proceed;
  (* src = "insn_decoder_new.v:16" *)
  input [4:0] mem_r1_a;
  (* src = "insn_decoder_new.v:16" *)
  input [4:0] mem_r2_a;
  (* src = "insn_decoder_new.v:17" *)
  input [3:0] mem_r_op;
  (* src = "insn_decoder_new.v:9" *)
  output reg_hazard;
  (* src = "insn_decoder_new.v:20" *)
  input [4:0] reg_r1_a;
  (* src = "insn_decoder_new.v:61" *)
  wire reg_r1_write_comp;
  (* src = "insn_decoder_new.v:20" *)
  input [4:0] reg_r2_a;
  (* src = "insn_decoder_new.v:62" *)
  wire reg_r2_write_comp;
  (* src = "insn_decoder_new.v:21" *)
  input [1:0] reg_write;
  INVX1 _168_ (
    .A(ex_proceed),
    .Y(_127_)
  );
  INVX1 _169_ (
    .A(dec_r_read[0]),
    .Y(_128_)
  );
  INVX1 _170_ (
    .A(dec_r_read[1]),
    .Y(_129_)
  );
  INVX1 _171_ (
    .A(ex_r_op[3]),
    .Y(_130_)
  );
  INVX1 _172_ (
    .A(dec_r1_addr[1]),
    .Y(_131_)
  );
  INVX1 _173_ (
    .A(dec_r1_addr[4]),
    .Y(_132_)
  );
  INVX1 _174_ (
    .A(dec_r2_addr[0]),
    .Y(_133_)
  );
  INVX1 _175_ (
    .A(dec_r2_addr[1]),
    .Y(_134_)
  );
  INVX1 _176_ (
    .A(dec_r2_addr[2]),
    .Y(_135_)
  );
  INVX1 _177_ (
    .A(dec_r2_addr[4]),
    .Y(_136_)
  );
  INVX1 _178_ (
    .A(mem_proceed),
    .Y(_137_)
  );
  INVX1 _179_ (
    .A(mem_r_op[3]),
    .Y(_138_)
  );
  INVX1 _180_ (
    .A(reg_r1_a[1]),
    .Y(_139_)
  );
  INVX1 _181_ (
    .A(reg_r1_a[3]),
    .Y(_140_)
  );
  INVX1 _182_ (
    .A(reg_r2_a[2]),
    .Y(_141_)
  );
  NOR2X1 _183_ (
    .A(ex_r_op[0]),
    .B(ex_r_op[1]),
    .Y(_142_)
  );
  NAND2X1 _184_ (
    .A(ex_r_op[3]),
    .B(_142_),
    .Y(_143_)
  );
  OAI21X1 _185_ (
    .A(ex_r_op[0]),
    .B(ex_r_op[1]),
    .C(_130_),
    .Y(_144_)
  );
  NAND2X1 _186_ (
    .A(ex_r_op[0]),
    .B(ex_r_op[1]),
    .Y(_145_)
  );
  AOI22X1 _187_ (
    .A(_143_),
    .B(_144_),
    .C(_145_),
    .D(ex_r_op[2]),
    .Y(_146_)
  );
  NAND2X1 _188_ (
    .A(ex_r1_a[0]),
    .B(ex_r1_a[1]),
    .Y(_147_)
  );
  NAND3X1 _189_ (
    .A(ex_r1_a[2]),
    .B(ex_r1_a[3]),
    .C(ex_r1_a[4]),
    .Y(_148_)
  );
  NOR2X1 _190_ (
    .A(_147_),
    .B(_148_),
    .Y(_149_)
  );
  NAND2X1 _191_ (
    .A(_130_),
    .B(ex_r_op[2]),
    .Y(_150_)
  );
  OAI21X1 _192_ (
    .A(ex_r_op[2]),
    .B(_143_),
    .C(_150_),
    .Y(_151_)
  );
  NAND2X1 _193_ (
    .A(ex_r2_a[0]),
    .B(ex_r2_a[1]),
    .Y(_152_)
  );
  NAND3X1 _194_ (
    .A(ex_r2_a[2]),
    .B(ex_r2_a[3]),
    .C(ex_r2_a[4]),
    .Y(_153_)
  );
  NOR2X1 _195_ (
    .A(_152_),
    .B(_153_),
    .Y(_154_)
  );
  AOI22X1 _196_ (
    .A(_146_),
    .B(_149_),
    .C(_151_),
    .D(_154_),
    .Y(_155_)
  );
  NOR2X1 _197_ (
    .A(mem_r_op[0]),
    .B(mem_r_op[1]),
    .Y(_156_)
  );
  NAND2X1 _198_ (
    .A(mem_r_op[3]),
    .B(_156_),
    .Y(_157_)
  );
  OAI21X1 _199_ (
    .A(mem_r_op[0]),
    .B(mem_r_op[1]),
    .C(_138_),
    .Y(_158_)
  );
  NAND2X1 _200_ (
    .A(mem_r_op[0]),
    .B(mem_r_op[1]),
    .Y(_159_)
  );
  AOI22X1 _201_ (
    .A(_157_),
    .B(_158_),
    .C(_159_),
    .D(mem_r_op[2]),
    .Y(_160_)
  );
  NAND2X1 _202_ (
    .A(mem_r1_a[0]),
    .B(mem_r1_a[1]),
    .Y(_161_)
  );
  NAND3X1 _203_ (
    .A(mem_r1_a[2]),
    .B(mem_r1_a[3]),
    .C(mem_r1_a[4]),
    .Y(_162_)
  );
  NOR2X1 _204_ (
    .A(_161_),
    .B(_162_),
    .Y(_163_)
  );
  NAND2X1 _205_ (
    .A(_138_),
    .B(mem_r_op[2]),
    .Y(_164_)
  );
  OAI21X1 _206_ (
    .A(mem_r_op[2]),
    .B(_157_),
    .C(_164_),
    .Y(_165_)
  );
  NAND2X1 _207_ (
    .A(mem_r2_a[0]),
    .B(mem_r2_a[1]),
    .Y(_166_)
  );
  NAND3X1 _208_ (
    .A(mem_r2_a[2]),
    .B(mem_r2_a[3]),
    .C(mem_r2_a[4]),
    .Y(_167_)
  );
  NOR2X1 _209_ (
    .A(_166_),
    .B(_167_),
    .Y(_000_)
  );
  AOI22X1 _210_ (
    .A(_160_),
    .B(_163_),
    .C(_165_),
    .D(_000_),
    .Y(_001_)
  );
  NAND2X1 _211_ (
    .A(reg_r2_a[1]),
    .B(reg_r2_a[4]),
    .Y(_002_)
  );
  NAND3X1 _212_ (
    .A(reg_write[1]),
    .B(reg_r2_a[2]),
    .C(reg_r2_a[3]),
    .Y(_003_)
  );
  NOR2X1 _213_ (
    .A(_002_),
    .B(_003_),
    .Y(_004_)
  );
  NAND2X1 _214_ (
    .A(reg_r2_a[0]),
    .B(_004_),
    .Y(_005_)
  );
  NAND3X1 _215_ (
    .A(reg_write[0]),
    .B(reg_r1_a[0]),
    .C(reg_r1_a[2]),
    .Y(_006_)
  );
  NAND3X1 _216_ (
    .A(reg_r1_a[1]),
    .B(reg_r1_a[3]),
    .C(reg_r1_a[4]),
    .Y(_007_)
  );
  OAI21X1 _217_ (
    .A(_137_),
    .B(_001_),
    .C(_005_),
    .Y(_008_)
  );
  OAI22X1 _218_ (
    .A(_127_),
    .B(_155_),
    .C(_006_),
    .D(_007_),
    .Y(_009_)
  );
  OR2X1 _219_ (
    .A(_008_),
    .B(_009_),
    .Y(jmp_hazard)
  );
  XNOR2X1 _220_ (
    .A(dec_r2_addr[3]),
    .B(ex_r2_a[3]),
    .Y(_010_)
  );
  AND2X1 _221_ (
    .A(dec_r2_addr[2]),
    .B(ex_r2_a[2]),
    .Y(_011_)
  );
  NOR2X1 _222_ (
    .A(dec_r2_addr[2]),
    .B(ex_r2_a[2]),
    .Y(_012_)
  );
  OAI21X1 _223_ (
    .A(_011_),
    .B(_012_),
    .C(_010_),
    .Y(_013_)
  );
  XNOR2X1 _224_ (
    .A(dec_r2_addr[1]),
    .B(ex_r2_a[1]),
    .Y(_014_)
  );
  XNOR2X1 _225_ (
    .A(dec_r2_addr[0]),
    .B(ex_r2_a[0]),
    .Y(_015_)
  );
  XNOR2X1 _226_ (
    .A(dec_r2_addr[4]),
    .B(ex_r2_a[4]),
    .Y(_016_)
  );
  NAND3X1 _227_ (
    .A(_014_),
    .B(_015_),
    .C(_016_),
    .Y(_017_)
  );
  NOR2X1 _228_ (
    .A(_013_),
    .B(_017_),
    .Y(_018_)
  );
  XNOR2X1 _229_ (
    .A(ex_r1_a[4]),
    .B(dec_r2_addr[4]),
    .Y(_019_)
  );
  XNOR2X1 _230_ (
    .A(ex_r1_a[2]),
    .B(dec_r2_addr[2]),
    .Y(_020_)
  );
  XNOR2X1 _231_ (
    .A(ex_r1_a[1]),
    .B(dec_r2_addr[1]),
    .Y(_021_)
  );
  XNOR2X1 _232_ (
    .A(ex_r1_a[3]),
    .B(dec_r2_addr[3]),
    .Y(_022_)
  );
  AND2X1 _233_ (
    .A(ex_r1_a[0]),
    .B(dec_r2_addr[0]),
    .Y(_023_)
  );
  NOR2X1 _234_ (
    .A(ex_r1_a[0]),
    .B(dec_r2_addr[0]),
    .Y(_024_)
  );
  OAI21X1 _235_ (
    .A(_023_),
    .B(_024_),
    .C(_022_),
    .Y(_025_)
  );
  NAND3X1 _236_ (
    .A(_019_),
    .B(_020_),
    .C(_021_),
    .Y(_026_)
  );
  NOR2X1 _237_ (
    .A(_025_),
    .B(_026_),
    .Y(_027_)
  );
  AOI22X1 _238_ (
    .A(_151_),
    .B(_018_),
    .C(_027_),
    .D(_146_),
    .Y(_028_)
  );
  XNOR2X1 _239_ (
    .A(dec_r1_addr[0]),
    .B(ex_r2_a[0]),
    .Y(_029_)
  );
  XNOR2X1 _240_ (
    .A(dec_r1_addr[1]),
    .B(ex_r2_a[1]),
    .Y(_030_)
  );
  XNOR2X1 _241_ (
    .A(dec_r1_addr[3]),
    .B(ex_r2_a[3]),
    .Y(_031_)
  );
  NOR2X1 _242_ (
    .A(dec_r1_addr[4]),
    .B(ex_r2_a[4]),
    .Y(_032_)
  );
  AND2X1 _243_ (
    .A(dec_r1_addr[4]),
    .B(ex_r2_a[4]),
    .Y(_033_)
  );
  XNOR2X1 _244_ (
    .A(dec_r1_addr[2]),
    .B(ex_r2_a[2]),
    .Y(_034_)
  );
  OAI21X1 _245_ (
    .A(_032_),
    .B(_033_),
    .C(_029_),
    .Y(_035_)
  );
  NAND3X1 _246_ (
    .A(_030_),
    .B(_031_),
    .C(_034_),
    .Y(_036_)
  );
  NOR2X1 _247_ (
    .A(_035_),
    .B(_036_),
    .Y(_037_)
  );
  XNOR2X1 _248_ (
    .A(dec_r1_addr[4]),
    .B(ex_r1_a[4]),
    .Y(_038_)
  );
  NOR2X1 _249_ (
    .A(dec_r1_addr[1]),
    .B(ex_r1_a[1]),
    .Y(_039_)
  );
  AND2X1 _250_ (
    .A(dec_r1_addr[1]),
    .B(ex_r1_a[1]),
    .Y(_040_)
  );
  OAI21X1 _251_ (
    .A(_039_),
    .B(_040_),
    .C(_038_),
    .Y(_041_)
  );
  XNOR2X1 _252_ (
    .A(dec_r1_addr[2]),
    .B(ex_r1_a[2]),
    .Y(_042_)
  );
  XNOR2X1 _253_ (
    .A(dec_r1_addr[3]),
    .B(ex_r1_a[3]),
    .Y(_043_)
  );
  XNOR2X1 _254_ (
    .A(dec_r1_addr[0]),
    .B(ex_r1_a[0]),
    .Y(_044_)
  );
  NAND3X1 _255_ (
    .A(_042_),
    .B(_043_),
    .C(_044_),
    .Y(_045_)
  );
  NOR2X1 _256_ (
    .A(_041_),
    .B(_045_),
    .Y(_046_)
  );
  AOI22X1 _257_ (
    .A(_151_),
    .B(_037_),
    .C(_046_),
    .D(_146_),
    .Y(_047_)
  );
  OAI22X1 _258_ (
    .A(_129_),
    .B(_028_),
    .C(_047_),
    .D(_128_),
    .Y(_048_)
  );
  AND2X1 _259_ (
    .A(ex_proceed),
    .B(_048_),
    .Y(ex_hazard)
  );
  XNOR2X1 _260_ (
    .A(dec_r2_addr[4]),
    .B(mem_r2_a[4]),
    .Y(_049_)
  );
  XNOR2X1 _261_ (
    .A(dec_r2_addr[2]),
    .B(mem_r2_a[2]),
    .Y(_050_)
  );
  XNOR2X1 _262_ (
    .A(dec_r2_addr[0]),
    .B(mem_r2_a[0]),
    .Y(_051_)
  );
  NOR2X1 _263_ (
    .A(dec_r2_addr[1]),
    .B(mem_r2_a[1]),
    .Y(_052_)
  );
  AND2X1 _264_ (
    .A(dec_r2_addr[1]),
    .B(mem_r2_a[1]),
    .Y(_053_)
  );
  XNOR2X1 _265_ (
    .A(dec_r2_addr[3]),
    .B(mem_r2_a[3]),
    .Y(_054_)
  );
  OAI21X1 _266_ (
    .A(_052_),
    .B(_053_),
    .C(_050_),
    .Y(_055_)
  );
  NAND3X1 _267_ (
    .A(_049_),
    .B(_051_),
    .C(_054_),
    .Y(_056_)
  );
  NOR2X1 _268_ (
    .A(_055_),
    .B(_056_),
    .Y(_057_)
  );
  XNOR2X1 _269_ (
    .A(dec_r2_addr[4]),
    .B(mem_r1_a[4]),
    .Y(_058_)
  );
  XNOR2X1 _270_ (
    .A(dec_r2_addr[2]),
    .B(mem_r1_a[2]),
    .Y(_059_)
  );
  XNOR2X1 _271_ (
    .A(dec_r2_addr[1]),
    .B(mem_r1_a[1]),
    .Y(_060_)
  );
  AND2X1 _272_ (
    .A(dec_r2_addr[3]),
    .B(mem_r1_a[3]),
    .Y(_061_)
  );
  NOR2X1 _273_ (
    .A(dec_r2_addr[3]),
    .B(mem_r1_a[3]),
    .Y(_062_)
  );
  XNOR2X1 _274_ (
    .A(dec_r2_addr[0]),
    .B(mem_r1_a[0]),
    .Y(_063_)
  );
  OAI21X1 _275_ (
    .A(_061_),
    .B(_062_),
    .C(_058_),
    .Y(_064_)
  );
  NAND3X1 _276_ (
    .A(_059_),
    .B(_060_),
    .C(_063_),
    .Y(_065_)
  );
  NOR2X1 _277_ (
    .A(_064_),
    .B(_065_),
    .Y(_066_)
  );
  AOI22X1 _278_ (
    .A(_165_),
    .B(_057_),
    .C(_066_),
    .D(_160_),
    .Y(_067_)
  );
  XNOR2X1 _279_ (
    .A(dec_r1_addr[2]),
    .B(mem_r2_a[2]),
    .Y(_068_)
  );
  XNOR2X1 _280_ (
    .A(dec_r1_addr[3]),
    .B(mem_r2_a[3]),
    .Y(_069_)
  );
  XNOR2X1 _281_ (
    .A(dec_r1_addr[1]),
    .B(mem_r2_a[1]),
    .Y(_070_)
  );
  NOR2X1 _282_ (
    .A(dec_r1_addr[4]),
    .B(mem_r2_a[4]),
    .Y(_071_)
  );
  AND2X1 _283_ (
    .A(dec_r1_addr[4]),
    .B(mem_r2_a[4]),
    .Y(_072_)
  );
  OAI21X1 _284_ (
    .A(_071_),
    .B(_072_),
    .C(_070_),
    .Y(_073_)
  );
  XNOR2X1 _285_ (
    .A(dec_r1_addr[0]),
    .B(mem_r2_a[0]),
    .Y(_074_)
  );
  NAND3X1 _286_ (
    .A(_068_),
    .B(_069_),
    .C(_074_),
    .Y(_075_)
  );
  NOR2X1 _287_ (
    .A(_073_),
    .B(_075_),
    .Y(_076_)
  );
  XNOR2X1 _288_ (
    .A(dec_r1_addr[2]),
    .B(mem_r1_a[2]),
    .Y(_077_)
  );
  XNOR2X1 _289_ (
    .A(dec_r1_addr[1]),
    .B(mem_r1_a[1]),
    .Y(_078_)
  );
  XNOR2X1 _290_ (
    .A(dec_r1_addr[4]),
    .B(mem_r1_a[4]),
    .Y(_079_)
  );
  NOR2X1 _291_ (
    .A(dec_r1_addr[3]),
    .B(mem_r1_a[3]),
    .Y(_080_)
  );
  AND2X1 _292_ (
    .A(dec_r1_addr[3]),
    .B(mem_r1_a[3]),
    .Y(_081_)
  );
  XNOR2X1 _293_ (
    .A(dec_r1_addr[0]),
    .B(mem_r1_a[0]),
    .Y(_082_)
  );
  OAI21X1 _294_ (
    .A(_080_),
    .B(_081_),
    .C(_078_),
    .Y(_083_)
  );
  NAND3X1 _295_ (
    .A(_077_),
    .B(_079_),
    .C(_082_),
    .Y(_084_)
  );
  NOR2X1 _296_ (
    .A(_083_),
    .B(_084_),
    .Y(_085_)
  );
  AOI22X1 _297_ (
    .A(_165_),
    .B(_076_),
    .C(_085_),
    .D(_160_),
    .Y(_086_)
  );
  OAI22X1 _298_ (
    .A(_129_),
    .B(_067_),
    .C(_086_),
    .D(_128_),
    .Y(_087_)
  );
  AND2X1 _299_ (
    .A(mem_proceed),
    .B(_087_),
    .Y(mem_hazard)
  );
  XNOR2X1 _300_ (
    .A(dec_r2_addr[0]),
    .B(reg_r1_a[0]),
    .Y(_088_)
  );
  AOI22X1 _301_ (
    .A(dec_r2_addr[1]),
    .B(_139_),
    .C(_140_),
    .D(dec_r2_addr[3]),
    .Y(_089_)
  );
  OAI21X1 _302_ (
    .A(dec_r2_addr[3]),
    .B(_140_),
    .C(_089_),
    .Y(_090_)
  );
  NAND2X1 _303_ (
    .A(reg_write[0]),
    .B(_088_),
    .Y(_091_)
  );
  NOR2X1 _304_ (
    .A(_090_),
    .B(_091_),
    .Y(_092_)
  );
  AOI22X1 _305_ (
    .A(_134_),
    .B(reg_r1_a[1]),
    .C(reg_r1_a[2]),
    .D(_135_),
    .Y(_093_)
  );
  OAI21X1 _306_ (
    .A(_135_),
    .B(reg_r1_a[2]),
    .C(_093_),
    .Y(_094_)
  );
  XOR2X1 _307_ (
    .A(dec_r2_addr[4]),
    .B(reg_r1_a[4]),
    .Y(_095_)
  );
  NOR2X1 _308_ (
    .A(_094_),
    .B(_095_),
    .Y(_096_)
  );
  OAI21X1 _309_ (
    .A(_133_),
    .B(reg_r2_a[0]),
    .C(reg_write[1]),
    .Y(_097_)
  );
  AND2X1 _310_ (
    .A(dec_r2_addr[1]),
    .B(reg_r2_a[1]),
    .Y(_098_)
  );
  NOR2X1 _311_ (
    .A(dec_r2_addr[1]),
    .B(reg_r2_a[1]),
    .Y(_099_)
  );
  AOI22X1 _312_ (
    .A(_133_),
    .B(reg_r2_a[0]),
    .C(reg_r2_a[2]),
    .D(_135_),
    .Y(_100_)
  );
  OAI21X1 _313_ (
    .A(_098_),
    .B(_099_),
    .C(_100_),
    .Y(_101_)
  );
  NOR2X1 _314_ (
    .A(_097_),
    .B(_101_),
    .Y(_102_)
  );
  XOR2X1 _315_ (
    .A(dec_r2_addr[3]),
    .B(reg_r2_a[3]),
    .Y(_103_)
  );
  AOI22X1 _316_ (
    .A(dec_r2_addr[2]),
    .B(_141_),
    .C(reg_r2_a[4]),
    .D(_136_),
    .Y(_104_)
  );
  OAI21X1 _317_ (
    .A(_136_),
    .B(reg_r2_a[4]),
    .C(_104_),
    .Y(_105_)
  );
  NOR2X1 _318_ (
    .A(_103_),
    .B(_105_),
    .Y(_106_)
  );
  AOI22X1 _319_ (
    .A(_092_),
    .B(_096_),
    .C(_102_),
    .D(_106_),
    .Y(_107_)
  );
  XOR2X1 _320_ (
    .A(dec_r1_addr[3]),
    .B(reg_r1_a[3]),
    .Y(_108_)
  );
  OAI21X1 _321_ (
    .A(_131_),
    .B(reg_r1_a[1]),
    .C(reg_write[0]),
    .Y(_109_)
  );
  NOR2X1 _322_ (
    .A(_108_),
    .B(_109_),
    .Y(_110_)
  );
  XNOR2X1 _323_ (
    .A(dec_r1_addr[2]),
    .B(reg_r1_a[2]),
    .Y(_111_)
  );
  OAI21X1 _324_ (
    .A(dec_r1_addr[1]),
    .B(_139_),
    .C(_111_),
    .Y(_112_)
  );
  XNOR2X1 _325_ (
    .A(dec_r1_addr[0]),
    .B(reg_r1_a[0]),
    .Y(_113_)
  );
  XNOR2X1 _326_ (
    .A(dec_r1_addr[4]),
    .B(reg_r1_a[4]),
    .Y(_114_)
  );
  NAND2X1 _327_ (
    .A(_113_),
    .B(_114_),
    .Y(_115_)
  );
  NOR2X1 _328_ (
    .A(_112_),
    .B(_115_),
    .Y(_116_)
  );
  OAI22X1 _329_ (
    .A(dec_r1_addr[2]),
    .B(_141_),
    .C(reg_r2_a[4]),
    .D(_132_),
    .Y(_117_)
  );
  AOI21X1 _330_ (
    .A(_132_),
    .B(reg_r2_a[4]),
    .C(_117_),
    .Y(_118_)
  );
  OAI21X1 _331_ (
    .A(_131_),
    .B(reg_r2_a[1]),
    .C(reg_write[1]),
    .Y(_119_)
  );
  XOR2X1 _332_ (
    .A(dec_r1_addr[3]),
    .B(reg_r2_a[3]),
    .Y(_120_)
  );
  OR2X1 _333_ (
    .A(_119_),
    .B(_120_),
    .Y(_121_)
  );
  XNOR2X1 _334_ (
    .A(dec_r1_addr[0]),
    .B(reg_r2_a[0]),
    .Y(_122_)
  );
  AOI22X1 _335_ (
    .A(_131_),
    .B(reg_r2_a[1]),
    .C(_141_),
    .D(dec_r1_addr[2]),
    .Y(_123_)
  );
  NAND2X1 _336_ (
    .A(_122_),
    .B(_123_),
    .Y(_124_)
  );
  NOR2X1 _337_ (
    .A(_121_),
    .B(_124_),
    .Y(_125_)
  );
  AOI22X1 _338_ (
    .A(_110_),
    .B(_116_),
    .C(_118_),
    .D(_125_),
    .Y(_126_)
  );
  OAI22X1 _339_ (
    .A(_129_),
    .B(_107_),
    .C(_126_),
    .D(_128_),
    .Y(reg_hazard)
  );
  assign dec_r1_read_comp = dec_r_read[0];
  assign dec_r2_read_comp = dec_r_read[1];
  assign reg_r1_write_comp = reg_write[0];
  assign reg_r2_write_comp = reg_write[1];
endmodule
