/* Generated by Yosys 0.7+307 (git sha1 7d41c5e1, gcc 7.2.0-3ubuntu1 -fPIC -Os) */

(* top =  1  *)
(* src = "passthrough.v:3" *)
module combined_ex_mem_passthrough(qm_a1, qm_a2, qm_r1_op, qm_r2_op, qr_a1, qr_a2, qr_op, qr_proceed, d1_r_a1, d1_r_a2, d1_r_op, m_a1, m_a2, m_r1_op, m_r2_op, r_a1, r_a2, r_op, r_proceed, clk, rst);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  (* src = "passthrough.v:11" *)
  input clk;
  (* src = "passthrough.v:20" *)
  output [4:0] d1_r_a1;
  (* src = "passthrough.v:20" *)
  output [4:0] d1_r_a2;
  (* src = "passthrough.v:21" *)
  output [3:0] d1_r_op;
  (* src = "passthrough.v:4" *)
  input [31:0] m_a1;
  (* src = "passthrough.v:4" *)
  input [31:0] m_a2;
  (* src = "passthrough.v:5" *)
  input [3:0] m_r1_op;
  (* src = "passthrough.v:5" *)
  input [3:0] m_r2_op;
  (* src = "passthrough.v:13" *)
  output [31:0] qm_a1;
  (* src = "passthrough.v:13" *)
  output [31:0] qm_a2;
  (* src = "passthrough.v:14" *)
  output [3:0] qm_r1_op;
  (* src = "passthrough.v:14" *)
  output [3:0] qm_r2_op;
  (* src = "passthrough.v:16" *)
  output [4:0] qr_a1;
  (* src = "passthrough.v:16" *)
  output [4:0] qr_a2;
  (* src = "passthrough.v:17" *)
  output [3:0] qr_op;
  (* src = "passthrough.v:18" *)
  output qr_proceed;
  (* src = "passthrough.v:7" *)
  input [4:0] r_a1;
  (* src = "passthrough.v:7" *)
  input [4:0] r_a2;
  (* src = "passthrough.v:8" *)
  input [3:0] r_op;
  (* src = "passthrough.v:9" *)
  input r_proceed;
  (* src = "passthrough.v:11" *)
  input rst;
  INVX1 _101_ (
    .A(rst),
    .Y(_000_)
  );
  INVX1 _102_ (
    .A(rst),
    .Y(_013_)
  );
  INVX1 _103_ (
    .A(rst),
    .Y(_024_)
  );
  INVX1 _104_ (
    .A(rst),
    .Y(_035_)
  );
  INVX1 _105_ (
    .A(rst),
    .Y(_046_)
  );
  INVX1 _106_ (
    .A(rst),
    .Y(_057_)
  );
  INVX1 _107_ (
    .A(rst),
    .Y(_068_)
  );
  INVX1 _108_ (
    .A(rst),
    .Y(_079_)
  );
  INVX1 _109_ (
    .A(rst),
    .Y(_090_)
  );
  INVX1 _110_ (
    .A(rst),
    .Y(_001_)
  );
  INVX1 _111_ (
    .A(rst),
    .Y(_004_)
  );
  INVX1 _112_ (
    .A(rst),
    .Y(_005_)
  );
  INVX1 _113_ (
    .A(rst),
    .Y(_006_)
  );
  INVX1 _114_ (
    .A(rst),
    .Y(_007_)
  );
  INVX1 _115_ (
    .A(rst),
    .Y(_008_)
  );
  INVX1 _116_ (
    .A(rst),
    .Y(_009_)
  );
  INVX1 _117_ (
    .A(rst),
    .Y(_010_)
  );
  INVX1 _118_ (
    .A(rst),
    .Y(_011_)
  );
  INVX1 _119_ (
    .A(rst),
    .Y(_012_)
  );
  INVX1 _120_ (
    .A(rst),
    .Y(_014_)
  );
  INVX1 _121_ (
    .A(rst),
    .Y(_015_)
  );
  INVX1 _122_ (
    .A(rst),
    .Y(_016_)
  );
  INVX1 _123_ (
    .A(rst),
    .Y(_017_)
  );
  INVX1 _124_ (
    .A(rst),
    .Y(_018_)
  );
  INVX1 _125_ (
    .A(rst),
    .Y(_019_)
  );
  INVX1 _126_ (
    .A(rst),
    .Y(_020_)
  );
  INVX1 _127_ (
    .A(rst),
    .Y(_021_)
  );
  INVX1 _128_ (
    .A(rst),
    .Y(_022_)
  );
  INVX1 _129_ (
    .A(rst),
    .Y(_023_)
  );
  INVX1 _130_ (
    .A(rst),
    .Y(_025_)
  );
  INVX1 _131_ (
    .A(rst),
    .Y(_026_)
  );
  INVX1 _132_ (
    .A(rst),
    .Y(_027_)
  );
  INVX1 _133_ (
    .A(rst),
    .Y(_028_)
  );
  INVX1 _134_ (
    .A(rst),
    .Y(_029_)
  );
  INVX1 _135_ (
    .A(rst),
    .Y(_030_)
  );
  INVX1 _136_ (
    .A(rst),
    .Y(_031_)
  );
  INVX1 _137_ (
    .A(rst),
    .Y(_032_)
  );
  INVX1 _138_ (
    .A(rst),
    .Y(_033_)
  );
  INVX1 _139_ (
    .A(rst),
    .Y(_034_)
  );
  INVX1 _140_ (
    .A(rst),
    .Y(_036_)
  );
  INVX1 _141_ (
    .A(rst),
    .Y(_037_)
  );
  INVX1 _142_ (
    .A(rst),
    .Y(_038_)
  );
  INVX1 _143_ (
    .A(rst),
    .Y(_039_)
  );
  INVX1 _144_ (
    .A(rst),
    .Y(_040_)
  );
  INVX1 _145_ (
    .A(rst),
    .Y(_041_)
  );
  INVX1 _146_ (
    .A(rst),
    .Y(_042_)
  );
  INVX1 _147_ (
    .A(rst),
    .Y(_043_)
  );
  INVX1 _148_ (
    .A(rst),
    .Y(_044_)
  );
  INVX1 _149_ (
    .A(rst),
    .Y(_045_)
  );
  INVX1 _150_ (
    .A(rst),
    .Y(_047_)
  );
  INVX1 _151_ (
    .A(rst),
    .Y(_048_)
  );
  INVX1 _152_ (
    .A(rst),
    .Y(_049_)
  );
  INVX1 _153_ (
    .A(rst),
    .Y(_050_)
  );
  INVX1 _154_ (
    .A(rst),
    .Y(_051_)
  );
  INVX1 _155_ (
    .A(rst),
    .Y(_052_)
  );
  INVX1 _156_ (
    .A(rst),
    .Y(_053_)
  );
  INVX1 _157_ (
    .A(rst),
    .Y(_054_)
  );
  INVX1 _158_ (
    .A(rst),
    .Y(_055_)
  );
  INVX1 _159_ (
    .A(rst),
    .Y(_056_)
  );
  INVX1 _160_ (
    .A(rst),
    .Y(_058_)
  );
  INVX1 _161_ (
    .A(rst),
    .Y(_059_)
  );
  INVX1 _162_ (
    .A(rst),
    .Y(_060_)
  );
  INVX1 _163_ (
    .A(rst),
    .Y(_061_)
  );
  INVX1 _164_ (
    .A(rst),
    .Y(_062_)
  );
  INVX1 _165_ (
    .A(rst),
    .Y(_063_)
  );
  INVX1 _166_ (
    .A(rst),
    .Y(_064_)
  );
  INVX1 _167_ (
    .A(rst),
    .Y(_065_)
  );
  INVX1 _168_ (
    .A(rst),
    .Y(_066_)
  );
  INVX1 _169_ (
    .A(rst),
    .Y(_067_)
  );
  INVX1 _170_ (
    .A(rst),
    .Y(_069_)
  );
  INVX1 _171_ (
    .A(rst),
    .Y(_070_)
  );
  INVX1 _172_ (
    .A(rst),
    .Y(_071_)
  );
  INVX1 _173_ (
    .A(rst),
    .Y(_072_)
  );
  INVX1 _174_ (
    .A(rst),
    .Y(_073_)
  );
  INVX1 _175_ (
    .A(rst),
    .Y(_074_)
  );
  INVX1 _176_ (
    .A(rst),
    .Y(_075_)
  );
  INVX1 _177_ (
    .A(rst),
    .Y(_076_)
  );
  INVX1 _178_ (
    .A(rst),
    .Y(_077_)
  );
  INVX1 _179_ (
    .A(rst),
    .Y(_078_)
  );
  INVX1 _180_ (
    .A(rst),
    .Y(_080_)
  );
  INVX1 _181_ (
    .A(rst),
    .Y(_081_)
  );
  INVX1 _182_ (
    .A(rst),
    .Y(_082_)
  );
  INVX1 _183_ (
    .A(rst),
    .Y(_083_)
  );
  INVX1 _184_ (
    .A(rst),
    .Y(_084_)
  );
  INVX1 _185_ (
    .A(rst),
    .Y(_085_)
  );
  INVX1 _186_ (
    .A(rst),
    .Y(_086_)
  );
  INVX1 _187_ (
    .A(rst),
    .Y(_087_)
  );
  INVX1 _188_ (
    .A(rst),
    .Y(_088_)
  );
  INVX1 _189_ (
    .A(rst),
    .Y(_089_)
  );
  INVX1 _190_ (
    .A(rst),
    .Y(_091_)
  );
  INVX1 _191_ (
    .A(rst),
    .Y(_092_)
  );
  INVX1 _192_ (
    .A(rst),
    .Y(_093_)
  );
  INVX1 _193_ (
    .A(rst),
    .Y(_094_)
  );
  INVX1 _194_ (
    .A(rst),
    .Y(_095_)
  );
  INVX1 _195_ (
    .A(rst),
    .Y(_096_)
  );
  INVX1 _196_ (
    .A(rst),
    .Y(_097_)
  );
  INVX1 _197_ (
    .A(rst),
    .Y(_098_)
  );
  INVX1 _198_ (
    .A(rst),
    .Y(_099_)
  );
  INVX1 _199_ (
    .A(rst),
    .Y(_100_)
  );
  INVX1 _200_ (
    .A(rst),
    .Y(_002_)
  );
  INVX1 _201_ (
    .A(rst),
    .Y(_003_)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _202_ (
    .CLK(clk),
    .D(m_a2[11]),
    .Q(qm_a2[11]),
    .R(_013_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _203_ (
    .CLK(clk),
    .D(m_a2[12]),
    .Q(qm_a2[12]),
    .R(_024_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _204_ (
    .CLK(clk),
    .D(m_a2[13]),
    .Q(qm_a2[13]),
    .R(_035_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _205_ (
    .CLK(clk),
    .D(m_a2[14]),
    .Q(qm_a2[14]),
    .R(_046_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _206_ (
    .CLK(clk),
    .D(m_a2[15]),
    .Q(qm_a2[15]),
    .R(_057_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _207_ (
    .CLK(clk),
    .D(m_a2[16]),
    .Q(qm_a2[16]),
    .R(_068_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _208_ (
    .CLK(clk),
    .D(m_a2[17]),
    .Q(qm_a2[17]),
    .R(_079_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _209_ (
    .CLK(clk),
    .D(m_a2[18]),
    .Q(qm_a2[18]),
    .R(_090_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _210_ (
    .CLK(clk),
    .D(m_a2[19]),
    .Q(qm_a2[19]),
    .R(_001_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _211_ (
    .CLK(clk),
    .D(m_a2[20]),
    .Q(qm_a2[20]),
    .R(_004_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _212_ (
    .CLK(clk),
    .D(m_a2[21]),
    .Q(qm_a2[21]),
    .R(_005_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _213_ (
    .CLK(clk),
    .D(m_a2[22]),
    .Q(qm_a2[22]),
    .R(_006_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _214_ (
    .CLK(clk),
    .D(m_a2[23]),
    .Q(qm_a2[23]),
    .R(_007_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _215_ (
    .CLK(clk),
    .D(m_a2[24]),
    .Q(qm_a2[24]),
    .R(_008_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _216_ (
    .CLK(clk),
    .D(m_a2[25]),
    .Q(qm_a2[25]),
    .R(_009_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _217_ (
    .CLK(clk),
    .D(m_a2[26]),
    .Q(qm_a2[26]),
    .R(_010_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _218_ (
    .CLK(clk),
    .D(m_a2[27]),
    .Q(qm_a2[27]),
    .R(_011_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _219_ (
    .CLK(clk),
    .D(m_a2[28]),
    .Q(qm_a2[28]),
    .R(_012_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _220_ (
    .CLK(clk),
    .D(m_a2[29]),
    .Q(qm_a2[29]),
    .R(_014_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _221_ (
    .CLK(clk),
    .D(m_a2[30]),
    .Q(qm_a2[30]),
    .R(_015_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _222_ (
    .CLK(clk),
    .D(m_a2[31]),
    .Q(qm_a2[31]),
    .R(_016_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _223_ (
    .CLK(clk),
    .D(m_r1_op[0]),
    .Q(qm_r1_op[0]),
    .R(_017_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _224_ (
    .CLK(clk),
    .D(m_r1_op[1]),
    .Q(qm_r1_op[1]),
    .R(_018_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _225_ (
    .CLK(clk),
    .D(m_r1_op[2]),
    .Q(qm_r1_op[2]),
    .R(_019_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _226_ (
    .CLK(clk),
    .D(m_r1_op[3]),
    .Q(qm_r1_op[3]),
    .R(_020_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _227_ (
    .CLK(clk),
    .D(m_r2_op[0]),
    .Q(qm_r2_op[0]),
    .R(_021_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _228_ (
    .CLK(clk),
    .D(m_r2_op[1]),
    .Q(qm_r2_op[1]),
    .R(_022_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _229_ (
    .CLK(clk),
    .D(m_r2_op[2]),
    .Q(qm_r2_op[2]),
    .R(_023_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _230_ (
    .CLK(clk),
    .D(m_r2_op[3]),
    .Q(qm_r2_op[3]),
    .R(_025_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _231_ (
    .CLK(clk),
    .D(d1_r_a1[0]),
    .Q(qr_a1[0]),
    .R(_026_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _232_ (
    .CLK(clk),
    .D(d1_r_a1[1]),
    .Q(qr_a1[1]),
    .R(_027_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _233_ (
    .CLK(clk),
    .D(d1_r_a1[2]),
    .Q(qr_a1[2]),
    .R(_028_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _234_ (
    .CLK(clk),
    .D(d1_r_a1[3]),
    .Q(qr_a1[3]),
    .R(_029_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _235_ (
    .CLK(clk),
    .D(d1_r_a1[4]),
    .Q(qr_a1[4]),
    .R(_030_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _236_ (
    .CLK(clk),
    .D(d1_r_a2[0]),
    .Q(qr_a2[0]),
    .R(_031_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _237_ (
    .CLK(clk),
    .D(d1_r_a2[1]),
    .Q(qr_a2[1]),
    .R(_032_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _238_ (
    .CLK(clk),
    .D(d1_r_a2[2]),
    .Q(qr_a2[2]),
    .R(_033_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _239_ (
    .CLK(clk),
    .D(d1_r_a2[3]),
    .Q(qr_a2[3]),
    .R(_034_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _240_ (
    .CLK(clk),
    .D(d1_r_a2[4]),
    .Q(qr_a2[4]),
    .R(_036_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _241_ (
    .CLK(clk),
    .D(d1_r_op[0]),
    .Q(qr_op[0]),
    .R(_037_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _242_ (
    .CLK(clk),
    .D(d1_r_op[1]),
    .Q(qr_op[1]),
    .R(_038_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _243_ (
    .CLK(clk),
    .D(d1_r_op[2]),
    .Q(qr_op[2]),
    .R(_039_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _244_ (
    .CLK(clk),
    .D(d1_r_op[3]),
    .Q(qr_op[3]),
    .R(_040_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _245_ (
    .CLK(clk),
    .D(r_proceed),
    .Q(qr_proceed),
    .R(_041_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _246_ (
    .CLK(clk),
    .D(r_a1[0]),
    .Q(d1_r_a1[0]),
    .R(_042_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _247_ (
    .CLK(clk),
    .D(r_a1[1]),
    .Q(d1_r_a1[1]),
    .R(_043_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _248_ (
    .CLK(clk),
    .D(r_a1[2]),
    .Q(d1_r_a1[2]),
    .R(_044_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _249_ (
    .CLK(clk),
    .D(r_a1[3]),
    .Q(d1_r_a1[3]),
    .R(_045_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _250_ (
    .CLK(clk),
    .D(r_a1[4]),
    .Q(d1_r_a1[4]),
    .R(_047_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _251_ (
    .CLK(clk),
    .D(r_a2[0]),
    .Q(d1_r_a2[0]),
    .R(_048_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _252_ (
    .CLK(clk),
    .D(r_a2[1]),
    .Q(d1_r_a2[1]),
    .R(_049_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _253_ (
    .CLK(clk),
    .D(r_a2[2]),
    .Q(d1_r_a2[2]),
    .R(_050_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _254_ (
    .CLK(clk),
    .D(r_a2[3]),
    .Q(d1_r_a2[3]),
    .R(_051_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _255_ (
    .CLK(clk),
    .D(r_a2[4]),
    .Q(d1_r_a2[4]),
    .R(_052_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _256_ (
    .CLK(clk),
    .D(r_op[0]),
    .Q(d1_r_op[0]),
    .R(_053_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _257_ (
    .CLK(clk),
    .D(r_op[1]),
    .Q(d1_r_op[1]),
    .R(_054_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _258_ (
    .CLK(clk),
    .D(r_op[2]),
    .Q(d1_r_op[2]),
    .R(_055_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _259_ (
    .CLK(clk),
    .D(r_op[3]),
    .Q(d1_r_op[3]),
    .R(_056_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _260_ (
    .CLK(clk),
    .D(m_a1[0]),
    .Q(qm_a1[0]),
    .R(_058_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _261_ (
    .CLK(clk),
    .D(m_a1[1]),
    .Q(qm_a1[1]),
    .R(_059_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _262_ (
    .CLK(clk),
    .D(m_a1[2]),
    .Q(qm_a1[2]),
    .R(_060_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _263_ (
    .CLK(clk),
    .D(m_a1[3]),
    .Q(qm_a1[3]),
    .R(_061_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _264_ (
    .CLK(clk),
    .D(m_a1[4]),
    .Q(qm_a1[4]),
    .R(_062_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _265_ (
    .CLK(clk),
    .D(m_a1[5]),
    .Q(qm_a1[5]),
    .R(_063_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _266_ (
    .CLK(clk),
    .D(m_a1[6]),
    .Q(qm_a1[6]),
    .R(_064_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _267_ (
    .CLK(clk),
    .D(m_a1[7]),
    .Q(qm_a1[7]),
    .R(_065_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _268_ (
    .CLK(clk),
    .D(m_a1[8]),
    .Q(qm_a1[8]),
    .R(_066_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _269_ (
    .CLK(clk),
    .D(m_a1[9]),
    .Q(qm_a1[9]),
    .R(_067_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _270_ (
    .CLK(clk),
    .D(m_a1[10]),
    .Q(qm_a1[10]),
    .R(_069_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _271_ (
    .CLK(clk),
    .D(m_a1[11]),
    .Q(qm_a1[11]),
    .R(_070_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _272_ (
    .CLK(clk),
    .D(m_a1[12]),
    .Q(qm_a1[12]),
    .R(_071_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _273_ (
    .CLK(clk),
    .D(m_a1[13]),
    .Q(qm_a1[13]),
    .R(_072_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _274_ (
    .CLK(clk),
    .D(m_a1[14]),
    .Q(qm_a1[14]),
    .R(_073_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _275_ (
    .CLK(clk),
    .D(m_a1[15]),
    .Q(qm_a1[15]),
    .R(_074_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _276_ (
    .CLK(clk),
    .D(m_a1[16]),
    .Q(qm_a1[16]),
    .R(_075_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _277_ (
    .CLK(clk),
    .D(m_a1[17]),
    .Q(qm_a1[17]),
    .R(_076_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _278_ (
    .CLK(clk),
    .D(m_a1[18]),
    .Q(qm_a1[18]),
    .R(_077_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _279_ (
    .CLK(clk),
    .D(m_a1[19]),
    .Q(qm_a1[19]),
    .R(_078_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _280_ (
    .CLK(clk),
    .D(m_a1[20]),
    .Q(qm_a1[20]),
    .R(_080_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _281_ (
    .CLK(clk),
    .D(m_a1[21]),
    .Q(qm_a1[21]),
    .R(_081_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _282_ (
    .CLK(clk),
    .D(m_a1[22]),
    .Q(qm_a1[22]),
    .R(_082_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _283_ (
    .CLK(clk),
    .D(m_a1[23]),
    .Q(qm_a1[23]),
    .R(_083_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _284_ (
    .CLK(clk),
    .D(m_a1[24]),
    .Q(qm_a1[24]),
    .R(_084_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _285_ (
    .CLK(clk),
    .D(m_a1[25]),
    .Q(qm_a1[25]),
    .R(_085_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _286_ (
    .CLK(clk),
    .D(m_a1[26]),
    .Q(qm_a1[26]),
    .R(_086_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _287_ (
    .CLK(clk),
    .D(m_a1[27]),
    .Q(qm_a1[27]),
    .R(_087_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _288_ (
    .CLK(clk),
    .D(m_a1[28]),
    .Q(qm_a1[28]),
    .R(_088_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _289_ (
    .CLK(clk),
    .D(m_a1[29]),
    .Q(qm_a1[29]),
    .R(_089_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _290_ (
    .CLK(clk),
    .D(m_a1[30]),
    .Q(qm_a1[30]),
    .R(_091_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _291_ (
    .CLK(clk),
    .D(m_a1[31]),
    .Q(qm_a1[31]),
    .R(_092_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _292_ (
    .CLK(clk),
    .D(m_a2[0]),
    .Q(qm_a2[0]),
    .R(_093_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _293_ (
    .CLK(clk),
    .D(m_a2[1]),
    .Q(qm_a2[1]),
    .R(_094_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _294_ (
    .CLK(clk),
    .D(m_a2[2]),
    .Q(qm_a2[2]),
    .R(_095_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _295_ (
    .CLK(clk),
    .D(m_a2[3]),
    .Q(qm_a2[3]),
    .R(_096_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _296_ (
    .CLK(clk),
    .D(m_a2[4]),
    .Q(qm_a2[4]),
    .R(_097_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _297_ (
    .CLK(clk),
    .D(m_a2[5]),
    .Q(qm_a2[5]),
    .R(_098_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _298_ (
    .CLK(clk),
    .D(m_a2[6]),
    .Q(qm_a2[6]),
    .R(_099_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _299_ (
    .CLK(clk),
    .D(m_a2[7]),
    .Q(qm_a2[7]),
    .R(_100_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _300_ (
    .CLK(clk),
    .D(m_a2[8]),
    .Q(qm_a2[8]),
    .R(_002_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _301_ (
    .CLK(clk),
    .D(m_a2[9]),
    .Q(qm_a2[9]),
    .R(_003_),
    .S(1'h1)
  );
  (* src = "passthrough.v:23" *)
  DFFSR _302_ (
    .CLK(clk),
    .D(m_a2[10]),
    .Q(qm_a2[10]),
    .R(_000_),
    .S(1'h1)
  );
endmodule
